### PR TITLE
feat(flask,wsgi): Add exemplars to metrics

### LINKED ISSUE #2158: Add exemplar support to all WSGI based instrumentations
**Describe the solution you'd like**
I would like that recorded spans from the WSGI instrumentation (in particular the Flask one) also provide exemplars. Currently there is no link between the spans and the related metrics.

**Describe alternatives you've considered**
Up to now, I used custom histogram and custom spans (in my own request handler). But this is redundant with the more integrated instrumentation setup.

**Additional context**
According to [the OTel documentation](https://opentelemetry.io/docs/specs/otel/metrics/sdk/#exemplar), any metric published inside an active span get linked as an exemplar. However, the latency of the handler seems [to be reported](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py#L596) after [the handler-span has ended](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py#L590). So no link is recorded between the span and the metric, while both are clearly related.

### PR DESCRIPTION
**Pull request by AlexisBRENON**
# Description

Close the request span after publishing the metrics to allow exemplar generation.

Fixes #2158 

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

TBD

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by xrmx** [comment]
@thanks for the PR, could you please rebase on latest main and fix conflicts please?

**Review by aabmass — CHANGES_REQUESTED** [review]
Check my comment https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2158#issuecomment-1936614527, this PR won't fix the issue

**Comment by AlexisBRENON** [comment]
Should I update it to make exemplars available as soon as it is in the SDK ?
Else, we should probably close the PR.

**Comment by ocelotl** [comment]
@AlexisBRENON Please reopen once exemplars are available in the SDK.

**Pull request closed without merging**
