### PR TITLE
Return none for Getter if key does not exist

### PR DESCRIPTION
**Pull request by lzchen**
Part of https://github.com/open-telemetry/opentelemetry-python/issues/1274

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Are tests already catching this? If not it would be good to have tests that do.

**Comment by lzchen** [comment]
@codeboten 
Yes each of these already has the empty use case test.

**Comment by lzchen** [comment]
@codeboten 
For asgi, the test is already covering this but I added headers for a more explicit check. For celery and wsgi, those cases will be covered by the propagator tests.

**Comment by lzchen** [comment]
@codeboten 
Nvm, I added tests.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
