### PR TITLE
Issue #1757 - Update HTTP server/client instrumentation span names

### LINKED ISSUE #1757: Update HTTP server/client instrumentation span names
Ref: https://github.com/open-telemetry/opentelemetry-specification/pull/3165

HTTP Server

   - {http.route} to {http.method} {http.route} (when route is available)
   - HTTP {http.method} to {http.method} (when route is not available)

HTTP Client

   - HTTP {http.method} to {http.method}

### PR DESCRIPTION
**Pull request by macieyng**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1757

**Scope**

SERVERS
- [x] asgi ([e67218a](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/e67218af809f071350009ac4195a18480f9b44e9), [e94660a](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/e94660ac80ac4bdf530c8f19d691ca2858dfdddc), [2c056d9](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/2c056d94b1613ae392693af592f945608fe570c0))
- [x] django ([5581bd5](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/5581bd56072f8aa1559d94bd5f5dc053adadbb7c), [370c656](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/370c6561076a208960db30967e76cadbc056face), [2d4abcd](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/2d4abcdfb78b7a495f8a89c1a1787aedc701373f))
- [x] falcon ([ef94b36](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/ef94b36707b33d8f7f06284931299daeff989b91))
- [x] flask ([ef94b36](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/ef94b36707b33d8f7f06284931299daeff989b91))
- [x] fastapi ([51e950c](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/51e950cf42e4b9e63bcfb755b0964dee4434800e))
- [x] pyramid ([ef94b36](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/ef94b36707b33d8f7f06284931299daeff989b91))
- [x] starlette ([c408058](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/c408058a1314adfabec1c1454f772a8ab49a9566), [adb73a7](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/adb73a7e1936e6191da3c9daae1fc2c8c4dd01a2))
- [x] tornado ([a749e77](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/a749e77a10a2cf8172977f4342afc04a6a630ae8), [2c056d9](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/2c056d94b1613ae392693af592f945608fe570c0))
- [x] wsgi ([22422e8](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/22422e8b4ad1ac26fe158af7e080bf2915f95dfe), [e94660a](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/e94660ac80ac4bdf530c8f19d691ca2858dfdddc), [2c056d9](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/2c056d94b1613ae392693af592f945608fe570c0))

CLIENTS
- [x] aiohttp ([d0b37c4](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/d0b37c459d502c384b1adec3868d9c372f1fe809))
- [x] httpx ([836c2c7](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/836c2c728a6ff85f230a4a1bd0fef2c777d3daeb))
- [x] requests ([1ea0970](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/1ea09706f92c84fb504132141ac75c921dd6f6a5))
- [x] urllib ([a0159a8](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/a0159a886faf79e2166d0f90ab2e317bf396f570))
- [x] urllib3 ([a88b5a0](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759/commits/a88b5a0ef7ca58660ccb97a4e37f06dbd4d30f3c))

## Type of change

- Bug fix (non-breaking change which fixes an issue)

**POTENTIAL BREAKING CHANGE** 
Specification change may be painful for projects that have alerting and analytics based on span names. The biggest impact would be for Tornado users then Django users, because span name was based on handler/function/view name. Proper warning should be included in release description.

# How Has This Been Tested?

I run `tox`.

# Does This PR Require a Core Repo Change?

- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by shalevr** [comment]
Please add a changelog entry that describes the change

**Comment by shalevr** [comment]
You need to run "tox -e lint"
or just the Python code formatter "black --config pyproject.toml ."

**Comment by macieyng** [comment]
I noticed that I skipped starlette. Will take care of it during the weekend.

**Comment by shalevr** [comment]
Some tests are failing, Please check if it is due to your change

**Comment by macieyng** [comment]
> Some tests are failing, Please check if it is due to your change

Yeah, that was the reason. Should be fixed now and sorry for replying so slow recently.

**Comment by macieyng** [comment]
@shalevr @srikanthccv ready for pipeline run.

**Comment by macieyng** [comment]
@shalevr @srikanthccv any idea why pipeline was cancelled or couldn't go through?

**Comment by macieyng** [comment]
Now it's failing because `remoulade` could not import `pydantic`. Progress 💪 😅

**Review by shalevr — APPROVED** [review]
Thanks

**Comment by macieyng** [comment]
@ocelotl @lzchen this PR is ready to be merged 🚀

**Pull request merged**
