### PR TITLE
Reorder on_finish call order to correctly instrument all tornado work done during a request

### LINKED ISSUE #495: Tornado instrumentation closes spans before on_finish is completed.
Ideally all trace spans in a request response cycle should be contained in one span. However because the tornado instrumentation library closes the span before calling the on_finish method. Orphaned spans from any instrumented code in on_finish method are created. Looking at the [code](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/__init__.py#L210-L212) a reordering would fix this situation. 

**Describe your environment** 

Python 3.8.5

requirements.txt
tornado==6.0.3

#tracing
opentelemetry-api==1.1.0
opentelemetry-sdk==1.1.0
opentelemetry-exporter-zipkin-json
opentelemetry-instrumentation
opentelemetry-instrumentation-dbapi
opentelemetry-instrumentation-tornado
opentelemetry-exporter-gcp-trace==1.0.0rc0

**Steps to reproduce**
Run the attached app below: 

`

import tornado.ioloop
import tornado.web
from opentelemetry import trace
from opentelemetry.trace import SpanKind

from opentelemetry import trace
from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter
from opentelemetry.exporter.zipkin.json import ZipkinExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (
    ConsoleSpanExporter,
    BatchSpanProcessor
)
from opentelemetry.instrumentation.tornado import TornadoInstrumentor

class MainHandler(tornado.web.RequestHandler):

    def on_finish(self) -> None:
        with trace.get_tracer(__name__).start_as_current_span("On finish test", kind=SpanKind.CLIENT) as span:
            print("Testing on finish span")

        super(MainHandler, self).on_finish()

    def get(self):
        self.write("Hello, world")

def init_tracing(is_deployment):
    resource = Resource.create(attributes={SERVICE_NAME: "Profile Service"})
    tracer_provider = TracerProvider(resource=resource)
    trace.set_tracer_provider(tracer_provider)

    if is_deployment:
        span_exporter = CloudTraceSpanExporter()
    else:
        # span_exporter = ZipkinExporter()
        span_exporter = ConsoleSpanExporter()

    span_processor = BatchSpanProcessor(span_exporter=span_exporter)
    trace.get_tracer_provider().add_span_processor(span_processor)

    TornadoInstrumentor().instrument()

def make_app():
    return tornado.web.Application([
        (r"/", MainHandler),
    ])

if __name__ == "__main__":

    init_tracing(is_deployment=False)
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
`

**What is the expected behavior?**
All traces in a request cycle should be contained in one span. However because the tornado instrumentation library closes the span before calling the on_finish method. This causes an orphaned span to be created.

**What is the actual behavior?**
Tornado instrumentation library should possibly run on_finish method before closing the main trace span

**Additional context**
I looked at the code and saw the affected part is [here ](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/__init__.py#L210-L212). Is there any reason to close the span before the parent on_finish method can be run?

### PR DESCRIPTION
**Pull request by pitabwire**
# Description

This PR ensures trace processing is closed only after tornado's on_finish method is called

Fixes #495 

## Type of change
-  [*] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Hey @pitabwire, thanks for the PR. Is it possible to add a test to capture the issue being fixed here?

Also please add an entry to CHANGELOG.md.

**Review by ocelotl — CHANGES_REQUESTED** [review]
Neat :sunglasses: 

Yes, please add a test, as requested by @codeboten :v:

**Review by owais — APPROVED** [review]

**Review by ocelotl — APPROVED** [review]
Nice :v:

**Review by lzchen — APPROVED** [review]

**Comment by lzchen** [comment]
@pitabwire 
Please fix the build errors and then we can merge this in!

**Review by codeboten — APPROVED** [review]

**Pull request merged**
