### PR TITLE
Remove SDK dependency from opentelemetry-instrumentation-grpc

### PR DESCRIPTION
**Pull request by aabmass**
# Description

Fixes https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2473

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [ ] Grepped through the code and we do not actually use the SDK anywhere outside of tests https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib%20path%3A%2F%5Einstrumentation%5C%2Fopentelemetry-instrumentation-grpc%5C%2F%2F%20sdk&type=code
- [ ] Existing tests pass fine

# Does This PR Require a Core Repo Change?

- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by xrmx — COMMENTED** [review]
The sdk is used directly in tests, should this be documented in the pyproject.toml?

**Comment by xrmx** [comment]
This appear to work here:

```
diff --git a/instrumentation/opentelemetry-instrumentation-grpc/tests/test_aio_server_interceptor.py b/instrumentation/opentelemetry-instrumentation-grpc/tests/test_aio_server_interceptor.py
index 7b31b085..06a919c4 100644
--- a/instrumentation/opentelemetry-instrumentation-grpc/tests/test_aio_server_interceptor.py
+++ b/instrumentation/opentelemetry-instrumentation-grpc/tests/test_aio_server_interceptor.py
@@ -39,10 +39,8 @@ from opentelemetry.instrumentation.grpc import (
     GrpcAioInstrumentorServer,
     aio_server_interceptor,
 )
-from opentelemetry.sdk import trace as trace_sdk
 from opentelemetry.semconv.trace import SpanAttributes
 from opentelemetry.test.test_base import TestBase
-from opentelemetry.trace import StatusCode
 
 from .protobuf.test_server_pb2 import Request, Response
 from .protobuf.test_server_pb2_grpc import (
@@ -391,7 +389,7 @@ class TestOpenTelemetryAioServerInterceptor(TestBase, IsolatedAsyncioTestCase):
 
         self.assertEqual(active_span_before_call, trace.INVALID_SPAN)
         self.assertEqual(active_span_after_call, trace.INVALID_SPAN)
-        self.assertIsInstance(active_span_in_handler, trace_sdk.Span)
+        self.assertIsInstance(active_span_in_handler, trace.Span)
         self.assertIsNone(active_span_in_handler.parent)
 
     async def test_sequential_server_spans(self):
@@ -536,7 +534,7 @@ class TestOpenTelemetryAioServerInterceptor(TestBase, IsolatedAsyncioTestCase):
         )
 
         # make sure this span errored, with the right status and detail
-        self.assertEqual(span.status.status_code, StatusCode.ERROR)
+        self.assertEqual(span.status.status_code, trace.StatusCode.ERROR)
         self.assertEqual(
             span.status.description,
             f"{grpc.StatusCode.INTERNAL}:{failure_message}",
@@ -601,7 +599,7 @@ class TestOpenTelemetryAioServerInterceptor(TestBase, IsolatedAsyncioTestCase):
         )
 
         # make sure this span errored, with the right status and detail
-        self.assertEqual(span.status.status_code, StatusCode.UNSET)
+        self.assertEqual(span.status.status_code, trace.StatusCode.UNSET)
         self.assertEqual(span.status.description, None)
 
         # Check attributes
```

**Comment by ocelotl** [comment]
> The sdk is used directly in tests, should this be documented in the pyproject.toml?

Not really, the test dependencies are defined in the `test-requirements-x.txt` files, the package dependencies are defined in `pyproject.toml`.

**Review by ocelotl — APPROVED** [review]

**Comment by xrmx** [comment]
> > The sdk is used directly in tests, should this be documented in the pyproject.toml?
> 
> Not really, the test dependencies are defined in the `test-requirements-x.txt` files, the package dependencies are defined in `pyproject.toml`.

yeah but we don't have the sdk in test-requirements

**Comment by ocelotl** [comment]
> > > The sdk is used directly in tests, should this be documented in the pyproject.toml?
> > 
> > 
> > Not really, the test dependencies are defined in the `test-requirements-x.txt` files, the package dependencies are defined in `pyproject.toml`.
> 
> yeah but we don't have the sdk in test-requirements

Yeah, that's an unfortunate consequence of our testing being done against a particular commit of the core repo, not a released version of the core repo. We have some test requirements in the `tox.ini` file (the ones that are core repo packages) and some other test requirements in the `test-requirements-x.txt` file.

**Comment by ocelotl** [comment]
@aabmass what do you think about @xrmx diff above?

**Comment by aabmass** [comment]
@xrmx I think since [`NonRecordingSpan` extends](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/trace/span.py#L513) the API Span, this change would always pass. I could ofc make it verify the span context is not empty/invalid.

That said, is there an issue with the tests using the SDK? That seems expected and the SDK is being installed in the test virtualenv

**Comment by aabmass** [comment]
@xrmx I think since [`NonRecordingSpan` extends](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/trace/span.py#L513) the API Span, this change would always pass. I could ofc make it verify the span context is not empty/invalid.

That said, is there an issue with the tests using the SDK? That seems expected and the SDK is being installed in the test virtualenv

**Comment by xrmx** [comment]
> @xrmx I think since [`NonRecordingSpan` extends](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/trace/span.py#L513) the API Span, this change would always pass. I could ofc make it verify the span context is not empty/invalid.
> 
> That said, is there an issue with the tests using the SDK? That seems expected and the SDK is being installed in the test virtualenv

I don't here's an issue in using the sdk, I think there's an issue in not declaring the dependency explicitly. Said that probably running just pytest after installing the test requirements is not working already so no big deal.

**Comment by aabmass** [comment]
> Said that probably running just pytest after installing the test requirements is not working already so no big deal.

Ya I think Diego's comment is right, since it's in `tox.ini` being installed from git HEAD, we don't want to add a hard requirement in the test-requirements.txt as a special case https://github.com/open-telemetry/opentelemetry-python-contrib/blob/5116305f77bcd4c8ab18ef302a4351bb5b724c1e/tox.ini#L444

**Pull request merged**
