### PR TITLE
Creating MANIFEST.in #1221

### PR DESCRIPTION
**Pull request by rahuldimri**
# Description

Manifest.ini file missing for the location from the below location.

[opentelemetry-python-contrib](https://github.com/open-telemetry/opentelemetry-python-contrib)/[instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation)/opentelemetry-instrumentation-aio-pika/

Fixes # 1221

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by srikanthccv** [comment]
You can add all missing files in just one PR as a part of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/893.

**Comment by rahuldimri** [comment]
@srikanthccv thank for the suggestion. As we 3 are working on this issue. We wanted to have this submitted from our own id.

If you still think this is not the correct way, We will open another PR for the same.

**Comment by srikanthccv** [comment]
I don't think this is such an issue that requires multiple PRs from multiple people. This is a trivial change that doesn't touch actual code. Please just create one PR with all the missing files.

**Comment by srikanthccv** [comment]
#1244

**Pull request closed without merging**
