### PR TITLE
Add NoOpTraceProvider test for opentelemetry-instrumentation-logging

### LINKED ISSUE #976: Audit and test opentelemetry-instrumentation-logging

### PR DESCRIPTION
**Pull request by the-chandru**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #976 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] tox -e test-instrumentation-logging

# Does This PR Require a Core Repo Change?

- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Unit tests have been added

### CODE REVIEW

**Comment by xrmx** [comment]
Please fix linting, you can configure pre-commit as written in CONTRIBUTING.md

**Comment by the-chandru** [comment]
> Please fix linting, you can configure pre-commit as written in CONTRIBUTING.md

Working on it!

**Comment by the-chandru** [comment]
@xrmx - The review comment has been addressed and the changes are pushed into PR. Thanks.

**Review by lzchen — APPROVED** [review]

**Comment by lzchen** [comment]
@the-chandru 

Please rebase with main so we can merge. Also if you can set pr settings to allow edits from maintainers, you can allow us to do this for you.

**Review by xrmx — APPROVED** [review]

**Comment by the-chandru** [comment]
> @the-chandru
> 
> Please rebase with main so we can merge. Also if you can set pr settings to allow edits from maintainers, you can allow us to do this for you.

Hello @lzchen  thanks for the approval, I am not sure if I have an option to allow edits from maintainers as my changes are through organization fork/repos. 

For the rebase, did you mean the option shown in the screenshot below?
image

**Comment by xrmx** [comment]
@the-chandru they are both fine

**Comment by the-chandru** [comment]
> @the-chandru they are both fine

Thanks @xrmx  I just did the rebase.

**Pull request merged**
