### PR TITLE
Update the psycopg2 dependency

### LINKED ISSUE #541: psycopg2-binary dependency conflict
**Describe your environment** 
```
> pip freeze | grep psyco
opentelemetry-instrumentation-psycopg2==0.22b0
psycopg2==2.8.6
```

**Steps to reproduce**
Install `psycopg2` instead of `psycopg2-binary`

**What is the expected behavior?**
No error message popping up

**What is the actual behavior?**
The instrumentation library will throw this error for every run.
```
DependencyConflict: requested: "psycopg2-binary >= 2.7.3.1" but found: "None"
```

**Additional context**
The instrumentation actually works as expected for `psycopg2`. So, the package instrumented should be both `psycopg2-binary` and `psycopg`

### PR DESCRIPTION
**Pull request by RyanSiu1995**
# Description
Fixes #541

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by owais — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Comment by RyanSiu1995** [comment]
Trying to fix the docker-tests right now

**Comment by RyanSiu1995** [comment]
I have tested it locally with `tox -e docker-tests`.
And the failed tests have all passed after changing the dependency inside `tox.ini`

**Comment by RyanSiu1995** [comment]
Hi @owais and @codeboten, could you mind helping me to re-review this?

**Review by owais — APPROVED** [review]

**Comment by cdvv7788** [comment]
Nice! Thanks!

**Pull request merged**
