### PR TITLE
Remove upper bound for dependency requirements

### LINKED ISSUE #668: Allow usage of httpx 0.19.*
httpx 0.19.0
opentelemetry-instrumentation-httpx 0.24b0

**Steps to reproduce**
Start the application.

**What is the expected behavior?**
No error messages.

**What is the actual behavior?**
`DependencyConflict: requested: "httpx >= 0.18.0, < 0.19.0" but found: "httpx 0.19.0"`

I'm wondering why opentelemetry-instrumentation-httpx is configured to support only 0.18.* and not anything above 0.19.*
If there are no concerns, could it allow 0.19.* as well?

https://github.com/open-telemetry/opentelemetry-python-contrib/blame/97e9f2f9ef6c775108ab30946a8668f64f37a4d9/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/package.py#L16

(Sorry. I opened it as a bug, but this is not a real bug).

### PR DESCRIPTION
**Pull request by ocelotl**
Fixes #668

### CODE REVIEW

**Review by owais — APPROVED** [review]

**Comment by jouve** [comment]
the limitation is enabled because of the handle_request API change in https://github.com/encode/httpx/blob/master/CHANGELOG.md#0200-13th-october-2021

**Comment by lzchen** [comment]
@ocelotl 
Is this PR still needed?

**Comment by jouve** [comment]
I think it would be better to update instrumentation-httpx to the new httpx API and make it depend on httpx >= 1.19 instead of 1.18

**Comment by owais** [comment]
When was 1.20 released? Is it too complex to support <1.20?

**Comment by ocelotl** [comment]
@lzchen it is an old draft, I honestly don't remember :sweat_smile: 

Closing to avoid confusion, if others have a solution for the corresponding issue it would be better to open a new PR :v:

**Pull request closed without merging**
