### PR TITLE
Call missing parent init

### LINKED ISSUE #1179: Instrumentation issues with coverage module and SQLite in latest 0.32b0 release
I utilize the automatic instrumentation for my projects during tests. When I run my [tests with coverage](https://coverage.readthedocs.io/en/6.4.1/) I get an error in the last part when the coverage results are being written out:

```
Traceback (most recent call last):
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/bin/coverage", line 8, in <module>
    sys.exit(main())
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/cmdline.py", line 943, in main
    status = CoverageScript().command_line(argv)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/cmdline.py", line 659, in command_line
    return self.do_run(options, args)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/cmdline.py", line 837, in do_run
    self.coverage.save()
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/control.py", line 706, in save
    data = self.get_data()
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/control.py", line 775, in get_data
    if self._collector and self._collector.flush_data():
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/collector.py", line 471, in flush_data
    self.covdata.add_arcs(self.mapped_file_dict(data))
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 238, in _wrapped
    return method(self, *args, **kwargs)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 499, in add_arcs
    self._choose_lines_or_arcs(arcs=True)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 528, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 315, in _connect
    self._open_db()
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 266, in _open_db
    self._read_db()
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 270, in _read_db
    with self._dbs[threading.get_ident()] as db:
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 1084, in __enter__
    self._connect()
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-auth-oHcJ824x-py3.10/lib/python3.10/site-packages/coverage/sqldata.py", line 1067, in _connect
    self.con.create_function("REGEXP", 2, _regexp)
sqlite3.ProgrammingError: Base Connection.__init__ not called.
```

An example execution for e.g. a Django project is this:

```
coverage run --rcfile pyproject.toml manage.py test
```

The only changes I have in my venv is the change from 1.12.0rc1 to 1.12.0rc2, and the contrib module from 0.31b0 to 0.32b0.

I can also reproduce this in some projects with Pytest, and the `pytest-cov` module:

```
pytest --cov --cov-report=xml:tests/coverage.xml
```

The way I kick off my instrumentation is to:

1. Add the `opentelemetry-contrib-instrumentations` dependency to pull in all instrumentations
2. Include a manual import to start monkeypatching:
    ```python
    # This import kicks off all of the autoinstrumentation of OpenTelemetry
    import opentelemetry.instrumentation.auto_instrumentation.sitecustomize as autotrace
    ```

**Steps to reproduce**

I'm working on a small example project that demonstrates the issue but wanted to get this open in the meantime to help others that might be googling for this issue. But basically:

0. Start instrumentation libraries
1. Run tests with coverage
2. At the end of the tests see the above error when attempting to write coverage data via sqlite

This causes the test process to get an error code and tests "fail". If I don't instrument then I don't get an error and everything works fine.

Python version - 3.10.4 (reproducible in Python 3.7-3.10)
OpenTelemetry/contrib Version - 1.12.0rc2/0.32b0
Coverage - 6.3.3 or 6.4.1
pytest-cov - 3.0.0

### PR DESCRIPTION
**Pull request by ocelotl**
Fixes #1179

### CODE REVIEW

**Review by phillipuniverse — CHANGES_REQUESTED** [review]
@ocelotl I think we're on the right track. I pulled in your changes and now I get this:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/pytest_cov/plugin.py", line 294, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/pytest_cov/engine.py", line 230, in finish
INTERNALERROR>     self.cov.stop()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/control.py", line 706, in save
INTERNALERROR>     data = self.get_data()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/control.py", line 775, in get_data
INTERNALERROR>     if self._collector and self._collector.flush_data():
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/collector.py", line 471, in flush_data
INTERNALERROR>     self.covdata.add_arcs(self.mapped_file_dict(data))
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 238, in _wrapped
INTERNALERROR>     return method(self, *args, **kwargs)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 499, in add_arcs
INTERNALERROR>     self._choose_lines_or_arcs(arcs=True)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 528, in _choose_lines_or_arcs
INTERNALERROR>     with self._connect() as con:
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 315, in _connect
INTERNALERROR>     self._open_db()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 266, in _open_db
INTERNALERROR>     self._read_db()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 270, in _read_db
INTERNALERROR>     with self._dbs[threading.get_ident()] as db:
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 1084, in __enter__
INTERNALERROR>     self._connect()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 1063, in _connect
INTERNALERROR>     self.con = sqlite3.connect(self.filename, check_same_thread=False)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 144, in wrap_connect_
INTERNALERROR>     return db_integration.wrapped_connection(wrapped, args, kwargs)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 267, in wrapped_connection
INTERNALERROR>     return get_traced_connection_proxy(connection, self)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 332, in get_traced_connection_proxy
INTERNALERROR>     return TracedConnectionProxy(connection)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 313, in __init__
INTERNALERROR>     super().__init__()
INTERNALERROR> TypeError: function missing required argument 'database' (pos 1)
```

Maybe we need to get at `*args` and `*kwargs` and pass those up? This stack trace is pretty informative with the `sqlite3.connect`

**Comment by ocelotl** [comment]
Ready, @phillipuniverse, please give it a try.

**Comment by phillipuniverse** [comment]
@ocelotl same exception but I'm not 100% sure if I've got the right reproduction case going on. Let me take a closer look here later.

But my suspicion is that probably need to propagate the `*args` and `**kwargs` when you construct the `TracedConnectionProxy` at https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1183/files#diff-554be8b86b646bc469f7e52d34360fb36743e0a584bd4322ad805d3df22d0001R332

**Comment by ocelotl** [comment]
> @ocelotl same exception but I'm not 100% sure if I've got the right reproduction case going on. Let me take a closer look here later.
> 
> But my suspicion is that probably need to propagate the `*args` and `**kwargs` when you construct the `TracedConnectionProxy` at https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1183/files#diff-554be8b86b646bc469f7e52d34360fb36743e0a584bd4322ad805d3df22d0001R332
> 
> image

Done :v:

**Comment by phillipuniverse** [comment]
Hm same exception, idk what's up here.

```
INTERNALERROR>     data = self.get_data()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/control.py", line 775, in get_data
INTERNALERROR>     if self._collector and self._collector.flush_data():
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/collector.py", line 471, in flush_data
INTERNALERROR>     self.covdata.add_arcs(self.mapped_file_dict(data))
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 238, in _wrapped
INTERNALERROR>     return method(self, *args, **kwargs)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 499, in add_arcs
INTERNALERROR>     self._choose_lines_or_arcs(arcs=True)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 528, in _choose_lines_or_arcs
INTERNALERROR>     with self._connect() as con:
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 315, in _connect
INTERNALERROR>     self._open_db()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 266, in _open_db
INTERNALERROR>     self._read_db()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 270, in _read_db
INTERNALERROR>     with self._dbs[threading.get_ident()] as db:
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 1084, in __enter__
INTERNALERROR>     self._connect()
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 1063, in _connect
INTERNALERROR>     self.con = sqlite3.connect(self.filename, check_same_thread=False)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 144, in wrap_connect_
INTERNALERROR>     return db_integration.wrapped_connection(wrapped, args, kwargs)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 267, in wrapped_connection
INTERNALERROR>     return get_traced_connection_proxy(connection, self)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 332, in get_traced_connection_proxy
INTERNALERROR>     return TracedConnectionProxy(connection, *args, **kwargs)
INTERNALERROR>   File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-common-python-zjZyLK7l-py3.7/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 313, in __init__
INTERNALERROR>     super().__init__(*args, **kwargs)
INTERNALERROR> TypeError: function missing required argument 'database' (pos 1)
```

We should have a much smaller reproduction case though of connecting to a file-based sqlite db. Running with the coverage module isn't particularly special, it's just creating a new SQLite db based on a file.

**Comment by phillipuniverse** [comment]
It's really unclear why the initial issue in #1179 was not [exposed by the tests](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/ee4083982f5919e1366de62b9cf4dac28cc8a314/instrumentation/opentelemetry-instrumentation-sqlite3/tests/test_sqlite3.py#L33). It seems like it's doing the same sort of `connect()` there.

But with the latest changes the tests do fail so at least there's some way to iterate. But I'm really not sure what the difference here is between what `coverage` is doing vs what vanilla SQLlite is doing.

**Comment by ocelotl** [comment]
@phillipuniverse Can you give it a try with the latest commit? I noticed that this latest commit seems to fix #1319, it may work here as well.

**Comment by alisonatwork** [comment]
I have run this test using the current commit as of 15 hours ago, and this is still broken for #1319, because args and kwargs are not set inside `get_traced_connection_proxy`.

What needs to happen is for the args and kwargs to be passed all of the way done from the top level. That is, `wrapped_connection` inside `DatabaseApiIntegration` should pass args and kwargs down to `get_traced_connection_proxy` and then into the `TracedConnectionProxy` constructor and its parent constructor.

I think for `instrument_connection` it should be okay to keep its `get_traced_connection_proxy` call as-is since it doesn't have any args or kwargs to relay.

**Comment by ocelotl** [comment]
@alisonatwork added your suggested changes, please give it a try :v:

**Comment by alisonatwork** [comment]
@ocelotl I dropped in the `__init__.py` only from the latest commit and commented out the sql comment refactoring churn that happened in #1224 (I still need to use 0.33b0 for Python 3.6 support) and the connection worked as expected.

**Comment by ocelotl** [comment]
> d in the `__init__.py` only from

Hm, sorry, I am a bit confused, can you paste a diff of your changes here against the latest commit on this PR, please?

**Comment by alisonatwork** [comment]
I can't run the current release of open telemetry in our project because Python 3.6 is no longer supported, so any fix applied upstream will not work for us until we upgrade Python. As such, I had to manually apply a partial diff of your changes to the 0.33b0 version installed in my venv to test it. The changes I had to make to get it running in my venv are unrelated to this PR and not important to fix the regression in the current version. Ideally this bug should've been fixed immediately after it was introduced in 0.32b0, before support for Python 3.6 was dropped in 0.34b0, but we'll find a way to work around it for our use case.

**Comment by phillipuniverse** [comment]
@ocelotl sorry I was out of pocket for a bit, I'll working on re-validating today or tomorrow.

**Comment by ocelotl** [comment]
[Test case](https://github.com/open-telemetry/opentelemetry-python-contrib/commit/36711ccd61a91ddce95dbf047ef8c8616bdd9c2d) that reproduces this issue by @rogersd.

**Comment by OrenZhang** [comment]
@ocelotl  hello, i wonder whether this issue would be fixed above 0.36b0, so i could upgrade to the latest version of opentelemetry sdk to test other features like `_log`

---

ps:
dbapi sdk doesn't work well since https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1097

**Comment by alisonatwork** [comment]
Please can someone prioritize addressing this issue, #1319 and #1179? The dbapi plugin has been broken for over 6 months now across multiple releases. It is hard to get buy-in for moving from proprietary tracing solutions to OpenTelemetry when such a fundamental feature is broken. The change in #1097 removed the functionality where custom args could be passed into the constructor of the underlying connection, so the fix is clear: all that needs to happen is to explicitly pass those args.

**Comment by phillipuniverse** [comment]
@ocelotl FWIW I pulled down your branch and ran my tests with the coverage module and have confirmed that the latest changes fixes the issue.

**Comment by phillipuniverse** [comment]
@ocelotl @srikanthccv any way we can prioritize getting this in for the release next week?

**Comment by philipcwhite** [comment]
If this fixes https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1179 then I'd like to see it added as well.  Thanks.

**Comment by philipcwhite** [comment]
Any chance this will get fixed in the near future?  I see it's not in the 0.37b0 release notes.  Thanks.

**Comment by phillipuniverse** [comment]
@philipcwhite this particular PR is not included in 0.37b0, but the revert of the change that caused the original problem is.

I confirmed that #1179 is resolved.

**Comment by philipcwhite** [comment]
@phillipuniverse I tested 0.37b0 and it does indeed fix the issue.  Thanks so much!

**Comment by ocelotl** [comment]
I won't be working on this PR for the foreseeable future, closing.

**Pull request closed without merging**
