### PR TITLE
Add AWS resource detector entry points

### LINKED ISSUE #1861: How to use OTEL_EXPERIMENTAL_RESOURCE_DETECTORS with contrib
Hello!

The `opentelemetry-python` package now supports specifying a list of resource detectors to automatically activate which is useful for auto instrumentation.  See https://github.com/open-telemetry/opentelemetry-python/pull/3181

Can this work with this contrib repo?  In particular ECS?

Thanks, Dan.

### LINKED ISSUE #2370: Using AWS resource detector with auto-instrumentation
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.

Running a basic Flask application instrumented using opentelemetry-instrument in Docker python:3.12.2-slim. Set environment variable `OTEL_EXPERIMENTAL_RESOURCE_DETECTORS=aws_ecs`.

Dependency versions:
* Flask==3.0.2
* opentelemetry-distro[otlp]==0.41b0
* opentelemetry-sdk-extension-aws==2.0.1

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

Run `docker-compose up -d` with entrypoint `opentelemetry-instrument flask run --host=0.0.0.0 --port=5000`

**What is the expected behavior?**
What did you expect to see?
Start up using ECS resource detector

**What is the actual behavior?**
What did you see instead?
```
web_1             | Distribution distro configuration failed
web_1             | Traceback (most recent call last):
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load.py",
line 40, in _load_distro
web_1             |     distro = entry_point.load()()
web_1             |              ^^^^^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py",
line 2471, in load
web_1             |     return self.resolve()
web_1             | ^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py",
line 2477, in resolve
web_1             |     module = __import__(self.module_name,
fromlist=['__name__'], level=0)
web_1             |
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/distro/__init__.py",
line 22, in <module>
web_1             |     from opentelemetry.sdk._configuration import
_OTelSDKConfigurator
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_configuration/__init__.py",
line 36, in <module>
web_1             |     from opentelemetry.sdk._logs import
LoggerProvider, LoggingHandler
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_logs/__init__.py",
line 16, in <module>
web_1             |     from opentelemetry.sdk._logs._internal import (
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py",
line 579, in <module>
web_1             |     class LoggerProvider(APILoggerProvider):
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py",
line 582, in LoggerProvider
web_1             |     resource: Resource = Resource.create(),
web_1             |                          ^^^^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/resources/__init__.py",
line 185, in create
web_1             |     next(
web_1             | StopIteration
web_1             | Failed to auto initialize opentelemetry
web_1             | Traceback (most recent call last):
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py",
line 36, in initialize
web_1             |     distro = _load_distro()
web_1             |              ^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load.py",
line 55, in _load_distro
web_1             |     raise exc
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load.py",
line 40, in _load_distro
web_1             |     distro = entry_point.load()()
web_1             |              ^^^^^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py",
line 2471, in load
web_1             |     return self.resolve()
web_1             |            ^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py",
line 2477, in resolve
web_1             |     module = __import__(self.module_name,
fromlist=['__name__'], level=0)
web_1             |
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/distro/__init__.py",
line 22, in <module>
web_1             |     from opentelemetry.sdk._configuration import
_OTelSDKConfigurator
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_configuration/__init__.py",
line 36, in <module>
web_1             |     from opentelemetry.sdk._logs import
LoggerProvider, LoggingHandler
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_logs/__init__.py",
line 16, in <module>
web_1             |     from opentelemetry.sdk._logs._internal import (
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py",
line 579, in <module>
web_1             |     class LoggerProvider(APILoggerProvider):
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py",
line 582, in LoggerProvider
web_1             |     resource: Resource = Resource.create(),
web_1             |                          ^^^^^^^^^^^^^^^^^
web_1             |   File
"/usr/local/lib/python3.11/site-packages/opentelemetry/sdk/resources/__init__.py",
line 185, in create
web_1             |     next(
web_1             | StopIteration
web_1             |  * Debug mode: on
web_1             | WARNING: This is a development server. Do not use it
in a production deployment. Use a production WSGI server instead.
web_1             |  * Running on all addresses (0.0.0.0)
web_1             |  * Running on http://127.0.0.1:4000/
web_1             |  * Running on http://192.168.48.3:4000/
web_1             | Press CTRL+C to quit
web_1             |  * Restarting with stat
web_1             |  * Debugger is active!
web_1             |  * Debugger PIN: 102-228-721
web_1             | 192.168.48.1 - - [26/Mar/2024 07:50:59] "GET /
HTTP/1.1" 200 -
```

**Additional context**

### PR DESCRIPTION
**Pull request by abstractOwl**
# Description
The AWS resource detectors currently are not picked up when using the new `OTEL_EXPERIMENTAL_RESOURCE_DETECTORS` environment variable because they are not registered under the [opentelemetry_resource_detector](https://github.com/open-telemetry/opentelemetry-python/blob/721beb8b530e7a830c1e27b70c2fb9af6465baf1/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L191-L194) entry point.

This PR adds the relevant section to the sdk-aws pyproject.toml file to allow the resource detectors to be used.

Fixes #1861, fixes #2370

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Added the following line to my Dockerfile in an otel-instrumented test Flask app:
```
RUN echo "\n\n[opentelemetry_resource_detector]\naws_elastic_beanstalk =
opentelemetry.sdk.extension.aws.resource.beanstalk:AwsBeanstalkResourceDetector"
 >>
/usr/local/lib/python3.12/site-packages/opentelemetry_sdk_extension_aws-2.0.1.dist-info/entry_points.txt
```

The logs showed that the relevant resource attributes were set:
```
web_1             | {
web_1             |     "resource_metrics": [
web_1             |         {
web_1             |             "resource": {
web_1             |                 "attributes": {
web_1             |                     "telemetry.sdk.language": "python",
web_1             |                     "telemetry.sdk.name":
"opentelemetry",
web_1             |                     "telemetry.sdk.version": "1.20.0",
web_1             |                     "cloud.provider": "aws",
web_1             |                     "cloud.platform":
"aws_elastic_beanstalk",
web_1             |                     "service.name": "otel_test",
web_1             |                     "service.instance.id": "abc123",
web_1             |                     "service.namespace": "12345",
web_1             |                     "service.version": "0.0.1",
web_1             |                     "telemetry.auto.version": "0.41b0"
web_1             |                 },
web_1             |                 "schema_url": ""
web_1             |             },
web_1             |             "scope_metrics": [],
web_1             |             "schema_url": ""
web_1             |         }
web_1             |     ]
web_1             | }
```

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by wangzlei — APPROVED** [review]
Thanks for contributing the PR. It looks good to me.

**Review by tammy-baylis-swi — APPROVED** [review]
Thank you for picking this one up. I'll trigger the checks.

**Comment by abstractOwl** [comment]
@tammy-baylis-swi: Thanks! I see that the lint is failing but I'm not sure that it's related to my changes

I also had two quick questions:
1. sdk-extension-aws seems to be [published separately](https://pypi.org/project/opentelemetry-sdk-extension-aws/#history) from the main sdk based on recent PyPi versions. Should I be updating the changelog if it's not technically part of the next release?
2. What is the process for getting these changes released?

**Comment by tammy-baylis-swi** [comment]
> the lint is failing but I'm not sure that it's related to my changes

Agreed, the same `not-context-manager` checks are failing on other PRs too after a recent merge. So not from your changes.

> What is the process for getting these changes released?

That's a good question. The extension's on the regular release [exclude list](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/24eadcf63d0d5dd78e38a88c2426439eb6e48e63/eachdist.ini#L51), and that release history predates my contributions 🙂 

I just found another issue from last year saying this package is not released anymore!!: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1899#issuecomment-1730397959 Please could you comment on that issue with a link to this PR?

**Comment by wangzlei** [comment]
IMO, the changelog update in this PR is ok, the repo maintainer will manage the remaining work.

There are [tow component maintainers](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/24eadcf63d0d5dd78e38a88c2426439eb6e48e63/.github/component_owners.yml#L35-L37C7). If @NathanielRN is not available, can @Kausik-A help take a look?

**Review by NathanielRN — APPROVED** [review]
LGTM! Thanks for contributing to open source :)

**Comment by lzchen** [comment]
@NathanielRN 

I believe we stopped releasing this package from the regular OpenTelemetry workflow on your request and haven't released it since. Is this extension still being supported, and if so, if we aren't releasing it as part of the regular workflow do we still want to keep it in the opentelemetry repo?

**Comment by NathanielRN** [comment]
@lzchen

Thanks for asking! This is a useful change and I imagine yes we would want it released. However I don't work on the AWS team that supports anymore and I want to make sure they have a say on its plans 😅 

@wangzlei do you know someone who can support the release of this package?

**Comment by lzchen** [comment]
Merging this for now.

@wangzlei 

If these aren't going to be released from this repository anymore, we will probably be discussing in removing it from OpenTelemetry soon.

**Comment by srprash** [comment]
> If these aren't going to be released from this repository anymore, we will probably be discussing in removing it from OpenTelemetry soon.

Similar issue calling out that the project containing these resource detectors is not included in the OTel release cycle. https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1899

It is tracked in the AWS backlog but not currently being worked on. cc: @vasireddy99 @vsakaram

@NathanielRN What was the reason for moving this package out of the OTel release? I don't see why we wouldn't want this released in sync with the rest of the packages.

**Comment by NathanielRN** [comment]
> @NathanielRN What was the reason for moving this package out of the OTel release? I don't see why we wouldn't want this released in sync with the rest of the packages.

@srprash this was a request our team made several years ago because we wanted to release it once we knew the release candidate was stable and wouldn't break AWS customers.

I would support joining the release cycle again for automatic release!

**Comment by srprash** [comment]
@lzchen What would it require to pull this package in the OTel's release cycles? I will be happy to help if you need.

**Comment by ocelotl** [comment]
I would prefer for this package to be moved out of this repo or integrated with the normal release process.

@NathanielRN @srprash are you ok with either of these options?

**Comment by srprash** [comment]
>integrated with the normal release process.

@ocelotl - I prefer this

**Comment by abstractOwl** [comment]
Any update here? @ocelotl @lzchen

**Comment by lzchen** [comment]
Continued discussion here https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1899

**Pull request merged**
