### PR TITLE
Fix install of Python 3.10 on GitHub Actions

### PR DESCRIPTION
**Pull request by tombruijn**
# Description

In PR #1604 the Python version was upgraded to Python 3.10 to fix a local issue on M1 MacBooks.

The GitHub Action workflows now exit with the following message for the docker-tests, spellcheck and lint checks, skipping these checks.

```
lint create: /home/runner/work/opentelemetry-python-contrib/opentelemetry-python-contrib/.tox/lint
SKIPPED: InterpreterNotFound: python3.10
___________________________________ summary ____________________________________
SKIPPED:  lint: InterpreterNotFound: python3.10
  congratulations :)
```

Upgrade the Python version in the GitHub Actions workflow to fix this.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Running the CI in full

# Does This PR Require a Core Repo Change?

- [x] No.

# Checklist:

- [x] Followed the style guidelines of this project

### CODE REVIEW

**Comment by tombruijn** [comment]
@ocelotl This seems important to fix the CI build :)

**Comment by tombruijn** [comment]
My bad. In YAML `3.10` != `"3.10"` and it failed on trying to install Python 3.1.

**Comment by tombruijn** [comment]
Please retry the build :) Should work now 🤞

**Comment by tombruijn** [comment]
Upgraded the dependencies that won't install on Python 3.10. Please retry the build again 😬 

Note to self: Don't multi task multiple fixes. I had them already upgraded for another PR I wanted to make, to fix the local build on M1 MacBooks, but turns out it's needed for this PR as well.

**Comment by tombruijn** [comment]
The changelog check failure is not something I can do I think? Does it need the "skip changelog" label?

**Review by srikanthccv — APPROVED** [review]

**Comment by srikanthccv** [comment]
Please fix the lint

**Comment by tombruijn** [comment]
I've fixed the issues that were merged into main. Let's merge this before more issues get merged into main.

I ignored a couple issue flagged pylint because fixing those would actually mean changing the implementation of those methods. You can find them by looking for the `# noqa pylint` comments in my commit.

**Review by srikanthccv — APPROVED** [review]

**Comment by tombruijn** [comment]
@srikanthccv the build passed! 🎉

**Comment by srikanthccv** [comment]
Thanks @tombruijn

**Comment by tombruijn** [comment]
Thanks for all the help @srikanthccv !

**Pull request merged**
