### PR TITLE
Fix unit in system metrics

### PR DESCRIPTION
**Pull request by bjrara**
# Description

Convert system metric to use UCUM to follow [OpenTelemetry semantic conventions](https://opentelemetry.io/docs/specs/semconv/system/system-metrics/)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by xrmx** [comment]
It can't hurt I guess, but aren't the names of the metrics out of spec?

**Comment by xrmx** [comment]
There is at least one other "bytes" usage, please update that too

**Comment by bjrara** [comment]
> There is at least another "bytes" usage, please update that too

Fixed it. Thank you!

**Comment by bjrara** [comment]
> It can't hurt I guess, but aren't the names of the metrics out of spec?

They aren't. But I guess this is the legacy we will need to carry until we find a deprecation path. For metric units fixes, I believe it is a reasonable change because the OTEL dependency services won't expect the units as `bytes` or `seconds` since it doesn't conform to the convention.

**Review by emdneto — APPROVED** [review]
LGTM since we are not changing metric names, ~but worried about this comment in semconv~:

~>SHOULD NOT adopt any breaking changes from document until the system semantic conventions are marked stable. Conventions include, but are not limited to, attributes, metric names, and unit of measure.~

~We are including unit of measure changes~

**Pull request merged**
