### PR TITLE
update requirements for snappy

### LINKED ISSUE #313: Docker tests are failing with AttributeError: module snappy has no attribute compress
This has been happening for a while; noticed some inconsistent behaviour but more frequent recently. Need to look into it and fix.

### PR DESCRIPTION
**Pull request by codeboten**
Fixes #313

### CODE REVIEW

**Review by aabmass — APPROVED** [review]
🦀 (snappy)

**Comment by alertedsnake** [comment]
Oh good!  I kept having to comment this out to do testing, as I'm not on a system with `apt`.

**Review by ocelotl — APPROVED** [review]

**Comment by haarakdy** [comment]
I am doing 
```
pip install opentelemetry-exporter-prometheus-remote-write
```
The outcome is
```
$ pip3 list | grep snappy
python-snappy                                  0.6.1       
snappy                                         3.0.3       
snappy-manifolds                               1.1.2    
```
What am I missing?

**Comment by haarakdy** [comment]
pip install opentelemetry-exporter-prometheus-remote-write

installs a wrong snappy package. It installs snappy geometry package.
The end result is that I get error

 "AttributeError: module 'snappy' has no attribute 'compress'".

**Comment by haarakdy** [comment]
A test 

```
pip3 install opentelemetry-exporter-prometheus-remote-write
```
```
from opentelemetry import metrics
from opentelemetry.exporter.prometheus_remote_write import PrometheusRemoteWriteMetricsExporter
from opentelemetry.sdk.metrics import Aggregator, MeterProvider, UpDownCounter, ValueRecorder


exporter = PrometheusRemoteWriteMetricsExporter(endpoint="https://listener.logz.io:8053", headers={"Authorization": f"Bearer ...",},)

metrics.set_meter_provider(MeterProvider())
meter = metrics.get_meter("test-meter")
metrics.get_meter_provider().start_pipeline(meter, exporter, 0.1)
new_metric = meter.create_updowncounter("test",description="", unit="1", value_type=float)
new_metric.add(0.1, labels={})
```


```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/sdk/metrics/export/controller.py", line 48, in run
    self.tick()
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/sdk/metrics/export/controller.py", line 60, in tick
    self.exporter.export(self.accumulator.processor.checkpoint_set())
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/exporter/prometheus_remote_write/__init__.py", line 173, in export
    message = self._build_message(timeseries)
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/exporter/prometheus_remote_write/__init__.py", line 325, in _build_message
    return snappy.compress(serialized_message)
AttributeError: module 'snappy' has no attribute 'compress'
```

**Comment by haarakdy** [comment]
The root cause is obviously 
This line 
```
./opentelemetry_exporter_prometheus_remote_write-0.17b0.dist-info/METADATA:Requires-Dist: snappy (>=2.8)
```
in the installation package https://pypi.org/project/opentelemetry-exporter-prometheus-remote-write/#files

**Pull request merged**
