### PR TITLE
Update semconv to 1.20.0

### PR DESCRIPTION
**Pull request by lmolkova**
# Description

Onboards instrumentations to fresh semantic conventions

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Run instrumentation tests

# Does This PR Require a Core Repo Change?

- [x] Yes. - Link to PR:  https://github.com/open-telemetry/opentelemetry-python/pull/3251
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by lmolkova** [comment]
this PR is ready for the review, @opentelemetry-python-contrib-approvers please take a look!

**Comment by ocelotl** [comment]
Thanks, @lmolkova, I am trying to debug the failing tests in the core repo.

**Comment by lmolkova** [comment]
@ocelotl it seems core tests fail on span name check.
`AssertionError: '"name": "HTTP GET"' not found in ... "name": "GET"`

 Span names were changed in #1759, but core tests were not updated to reflect it. I'm not sure what was the reason to remove `HTTP  " from client span names, LMK what should be fixed - the name or the core tests. Thanks!

**Comment by ocelotl** [comment]
> @ocelotl it seems core tests fail on span name check. `AssertionError: '"name": "HTTP GET"' not found in ... "name": "GET"`
> 
> Span names were changed in #1759, but core tests were not updated to reflect it. I'm not sure what was the reason to remove `HTTP " from client span names, LMK what should be fixed - the name or the core tests. Thanks!

Right, I just filed [this](https://github.com/open-telemetry/opentelemetry-python/issues/3367) issue, will take care of it, thanks!

**Comment by srikanthccv** [comment]
I think @lzchen had some points around the transition plan. Bringing this up in the SIG meeting (again) might be a good idea.

**Comment by ocelotl** [comment]
> I think @lzchen had some points around the transition plan. Bringing this up in the SIG meeting (again) might be a good idea.

Added to the SIG notes.

**Comment by lmolkova** [comment]
Closing this one.

Schema URL is populated in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1977, and @lzchen will prototype side-by-side new/old semconv in selected instrumentations

**Pull request closed without merging**
