### PR TITLE
NoOpTracerProvider test case for botocore instrumentation

### PR DESCRIPTION
**Pull request by Sunilwali679**
Adds NoOpTracerProvider test cases for botocore instrumentation.

Fixes https://github.com/open-telemetry/opentelemetry-python-contrib/issues/988

How Has This Been Tested?
tox -e test-instrumentation-botocore

Does This PR Require a Core Repo Change?

### CODE REVIEW

**Review by lzchen — APPROVED** [review]

**Comment by lzchen** [comment]
@Sunilwali679 

Please rebase and allow maintainers commits.

**Review by emdneto — APPROVED** [review]

**Comment by xrmx** [comment]
@Sunilwali679 please setup pre-commit (and fix linting) and rebase

**Comment by Sunilwali679** [comment]
@xrmx  Done the rebase and submitted for review

**Comment by xrmx** [comment]
> @xrmx Done the rebase and submitted for review

It looks like you missed the pre-commit setup :sweat_smile:

**Pull request closed without merging**
