### PR TITLE
Fix broken links to projects

### PR DESCRIPTION
**Pull request by cynthiakedu**
Fixes broken links to project in a few READMEs, closes https://github.com/open-telemetry/opentelemetry-python-contrib/issues/323.

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Nice! Thanks for fixing these, happy to review once its out of draft

**Review by owais — APPROVED** [review]

**Comment by owais** [comment]
Thanks. Would be great to have the same thing for the metrics branch as well. It'd be more useful there as people can discover the source more easily from pypi

**Comment by cynthiakedu** [comment]
Is the best way to do that just to create another PR? (and also assuming that I need to change the CHANGELOG PR number?)

**Comment by owais** [comment]
@cynthiakedu Yes, another PR for that makes sense if you want to take that on. Thanks

**Review by codeboten — APPROVED** [review]
Please update the branch and we can merge!

**Pull request merged**
