### PR TITLE
Update .instrument() call `response_hook` argument name in the documentation for Botocore and Pymongo

### PR DESCRIPTION
**Pull request by rahulgupta92**
# Description

The current documentation for Botocore and Pymongo instrumentation has incorrectly specified the argument `response_hook` as `response_hooks` for the `.instrument()` call. This PR fixes the argument name to use `response_hook` instead.

Correct Format:
`BotocoreInstrumentor().instrument(request_hook=request_hook, response_hook=response_hook)`

`PymongoInstrumentor().instrument(request_hook=request_hook, response_hook=response_hook, failed_hook=failed_hook)
`
## Type of change

- [X] This change requires a documentation update

# How Has This Been Tested?

All tests of the project have been run. 

# Does This PR Require a Core Repo Change?

- [X] No.

# Checklist:

- [X] Documentation has been updated

### CODE REVIEW

**Review by srikanthccv — APPROVED** [review]
Thank you @rahulgupta92. Please sign the CLA.

**Comment by rahulgupta92** [comment]
> Thank you @rahulgupta92. Please sign the CLA.

Have signed the CLA @srikanthccv

**Comment by srikanthccv** [comment]
@rahulgupta92 Either you didn't sign the cla completely or EasyCLA is not working. Please check again.

**Comment by rahulgupta92** [comment]
> @rahulgupta92 Either you didn't sign the cla completely or EasyCLA is not working. Please check again.

@srikanthccv  I have signed multiple times now as an Individual Contributor but it redirects me to this page after signing it successfully without any change in the PR status. Anything which i am missing? Does this need to be done via Corporate Contributor route only?

**Review by lzchen — APPROVED** [review]

**Pull request merged**
