### PR TITLE
[WIP]: SQLAlchemy & psycopg2 Flask Integration

### PR DESCRIPTION
**Pull request by Thiyagu55**
# SQLAlchemy & Psycopg2 SQLCommenter support for Flask related metrics

Support for using flask related metrics in sqlalchemy & psycopg2 SQL commenter.

This can be achieved by enabling enable_commenter flag inside Flask instrument initialization and also in SQLAlchemy Instrumentation  or psycopg2 instrumentation

```python
FlaskInstrumentor().instrument_app(app, tracer_provider=provider, enable_commenter=True)

# For sqlalchemy
SQLAlchemyInstrumentor().instrument( enable_commenter=True, engine=engine)

# For psycopg2
Psycopg2Instrumentor().instrument(tracer_provider=tracer_provider, enable_commenter=True)
```

- The flask instrumentation will append the metrics in opentelemetry context in key name SQLCOMMENTER_VALUES
- The SQLAlchemy ORM or psycopg2 driver will read the context and then append these info to the sql query logs whenever the sql query is made

@srikanthccv Need your suggestions for this draft PR so we could implement in full scale

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

Tests needs to be added upon approval of this solution

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by srikanthccv** [comment]
@Thiyagu55 this is probably not the best way to go about it. We can't do this for all instrumentation. Maybe we should make use of the context? The sqlcommenter will the read the request meta from the current context and frameworks can independently set meta in context.

**Comment by Thiyagu55** [comment]
> @Thiyagu55 this is probably not the best way to go about it. We can't do this for all instrumentation. Maybe we should make use of the context? The sqlcommenter will the read the request meta from the current context and frameworks can independently set meta in context.

@srikanthccv Updated the code so that the interchange takes place via context. Could you verify?

**Comment by srikanthccv** [comment]
@Thiyagu55 I would like to see what other approvers/maintainers think of this approach first and see if they have any other ideas.

**Comment by Thiyagu55** [comment]
> @Thiyagu55 I would like to see what other approvers/maintainers think of this approach first and see if they have any other ideas.

Sure

**Comment by Thiyagu55** [comment]
> > @Thiyagu55 I would like to see what other approvers/maintainers think of this approach first and see if they have any other ideas.
> 
> Sure

@srikanthccv Can you tag other reviewers for their opinion on this approach?

**Comment by srikanthccv** [comment]
@Thiyagu55 Sorry, haven't been able to bring this up in SIG because some approver/maintainers were OOO. Would you be able to join SIG meeting this week?

**Comment by Thiyagu55** [comment]
> @Thiyagu55 Sorry, haven't been able to bring this up in SIG because some approver/maintainers were OOO. Would you be able to join SIG meeting this week?

@sjs994 FYA

**Comment by Thiyagu55** [comment]
> > @Thiyagu55 Sorry, haven't been able to bring this up in SIG because some approver/maintainers were OOO. Would you be able to join SIG meeting this week?
> 
> @sjs994 FYA

@srikanthccv Subhrajyoti and me will attend the meeting tonight

**Comment by Thiyagu55** [comment]
Implemented in [https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1224](url)

**Pull request closed without merging**
