### PR TITLE
2677 jinja2 semconv

### LINKED ISSUE #2677: opentelemetry-instrumentation-jinja2: semantic convention stability migration
### What problem do you want to solve?
 
semantic convention stability migration for `opentelemetry-instrumentation-jinja2`.

### Describe the solution you'd like
Implement the semconv opt-in feature for jinja2

### Describe alternatives you've considered

_No response_

### Additional Context

Part of this https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2453

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by the-chandru**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2677 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] tox -e test-instrumentation-jinja2

# Does This PR Require a Core Repo Change?

- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by the-chandru** [comment]
Hi @ocelotl,

I have made the update to changelog, will be pushing it soon.

**Comment by lzchen** [comment]
@the-chandru 

Since there are no stable semantic conventions for templating we probably won't start this work. @emdneto Not sure if there will ever be stable sem convs from templating libraries, should we remove this from the list of migrations?

**Comment by emdneto** [comment]
> @the-chandru
> 
> Since there are no stable semantic conventions for templating we probably won't start this work. @emdneto @ocelotl @xrmx Not sure if there will ever be stable sem convs from templating libraries, should we remove this from the list of migrations?

I'm okay with that. I failed to find a relationship with any attributes we have in the recent version. The closest attributes I found were `file` attributes (https://opentelemetry.io/docs/specs/semconv/attributes-registry/file/). Since we have another migration work in progress [here](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2790) I think it's okay to drop this.

**Comment by lzchen** [comment]
Discussed during the 08/15/2024 Python SIG.

We will be removing jinja from the list of required instrumentations to carry the migration plan since there does not seem to be semantic conventions defined for it.

**Pull request closed without merging**
