### PR TITLE
Changed the format of traceparent id

### PR DESCRIPTION
**Pull request by Thiyagu55**
# Changed the format of traceparent id

Compressed the format of traceparent id from `/*span_id=16659691402252420308,trace_flags=1,trace_id=283190570959089573593920162873354610508,trace_state=''*/` to `/*traceparent='00-91be8b5a37d16542524ae5ae0907ec5f-543bfa9675358c75-1'*/`

## Type of change

Please delete options that are not relevant.

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [X] tox -e test-instrumentation-dbapi                                         

# Does This PR Require a Core Repo Change?

- [X] Yes. - Link to [PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/924/files#diff-4bf18e7d840238995e3eb1152d6bf0a3f56ce6ab6f2bcf1726ecbac7a79afedb) 

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [X] Changelogs have been updated

### CODE REVIEW

**Comment by ocelotl** [comment]
What issue is being fixed by this PR, @Thiyagu55 ?

**Comment by Thiyagu55** [comment]
> What issue is being fixed by this PR, @Thiyagu55 ?

@ocelotl This is not a bug fix issue.
Changed the format of traceparent id in query log

**Comment by srikanthccv** [comment]
@ocelotl The current format is not complaint with the commenter specification. This change fixes it.

**Comment by lzchen** [comment]
@Thiyagu55 
Could you link to the section of the sqlcommenter documentation in which it specifies the format of traceparent?

**Comment by Thiyagu55** [comment]
> @Thiyagu55
> Could you link to the section of the sqlcommenter documentation in which it specifies the format of traceparent?
https://open-telemetry.github.io/opentelemetry-sqlcommenter/

**Comment by lzchen** [comment]
Nit: Can you use f strings for [this](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/opentelemetry-instrumentation/src/opentelemetry/instrumentation/utils.py#L163)

**Comment by lzchen** [comment]
@srikanthccv 
Do you think `_generate_sql_comment` would always be used in conjuction with `_generate_opentelemetry_traceparent`? Is it necessary to separate these?

**Comment by srikanthccv** [comment]
@lzchen traceparent header is only part of the comment, there can be more info embedded in the comment such as request route. I think it is fine they are separate.

**Review by lzchen — APPROVED** [review]

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
