### PR TITLE
Conditionally create server spans for tornado and refactoring other frameworks to use utility function

### LINKED ISSUE #450: Tornado:  Conditionally create SERVER spans
Part of #445

### PR DESCRIPTION
**Pull request by ashu658**
# Description

- Adds support to make spans as INTERNAL if a span is already present in current context in tornado.
- Refactoring code in Django, Pyramid, Flask to use the utility funciton i.e. _start_internal_or_server_span

Fixes #450 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Currently falcon only makes SERVER spans. With this PR it can make INTERNAL spans in presence of a span in current context.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Does This PR Require a Core Repo Change?
 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by owais** [comment]
This contains changes to Django, Pyramid and Flask but PR claims to only add support for Tornado. I'd suggest to split out any refactor to another PR.

**Review by owais — APPROVED** [review]

**Comment by ashu658** [comment]
@owais Can you help me with the failing 'Combine benchmarks from previous build job'? I am not sure how to fix this.

**Comment by owais** [comment]
Just re-run it and hope it passes next time :) If it keeps failing consistently then we need to identify the performane degradation and fix it or update the perf numbers

**Comment by ashu658** [comment]
I guess I don't have the access to re-run tests. Can you re-run the test @owais ?

**Pull request merged**
