### PR TITLE
Send log level to log hook

### PR DESCRIPTION
**Pull request by nozik**
# Description

Add a log level param to the logging instrumentation `log_hook`.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Enhanced the existing log_hook test.

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [X] Unit tests have been added
- [X] Documentation has been updated

### CODE REVIEW

**Comment by srikanthccv** [comment]
What is new this adding? Don't you already have the level in `LogRecord`?

**Comment by nozik** [comment]
@srikanthccv Unfortunately no - the log level isn't available as part of the record itself

**Comment by srikanthccv** [comment]
That can't be true? There is both text (`levelname`) and numeric (`levelno`) [attributes](https://docs.python.org/3/library/logging.html#logrecord-attributes).

**Comment by nozik** [comment]
@srikanthccv Correct, my mistake. Closing the PR

**Pull request closed without merging**
