### PR TITLE
Hotfix for previous release

### PR DESCRIPTION
**Pull request by lzchen**
Fixes https://github.com/open-telemetry/opentelemetry-python-contrib/issues/346

### CODE REVIEW

**Review by owais — APPROVED** [review]
LGTM. Thanks

**Comment by owais** [comment]
@lzchen I see we are downgrading dependencies to older version. Will these work with latest API and SDK packages or does this mean users will also have to downgrade API and SDK?

**Comment by lzchen** [comment]
@owais 
Which dependencies are you referring to? 1.0.0rc1 are the latest for API and SDK.
If you are referring to `opentelemetry-instrumentation`, I could bump the version up to use 0.18b0 (which is latest)?

**Comment by owais** [comment]
Yes, I meant the instrumentations pinning opentelemetry-instrumentation==0.17b0. I tried the following and pip installs 0.17b0 for all packages.

```
❯ pip install opentelemetry-api opentelemetry-sdk opentelemetry-distro opentelemetry-instrumentation==0.17b0
Collecting opentelemetry-api
  Using cached opentelemetry_api-1.0.0rc1-py3-none-any.whl (36 kB)
Collecting opentelemetry-sdk
  Using cached opentelemetry_sdk-1.0.0rc1-py3-none-any.whl (35 kB)
Collecting opentelemetry-distro
  Using cached opentelemetry_distro-0.18b0-py3-none-any.whl (4.4 kB)
Collecting opentelemetry-instrumentation==0.17b0
  Using cached opentelemetry_instrumentation-0.17b0-py3-none-any.whl (15 kB)
Collecting wrapt<2.0.0,>=1.0.0
  Using cached wrapt-1.12.1-cp37-cp37m-macosx_10_15_x86_64.whl
Collecting opentelemetry-api
  Using cached opentelemetry_api-0.17b0-py3-none-any.whl (42 kB)
Collecting opentelemetry-distro
  Downloading opentelemetry_distro-0.17b0-py3-none-any.whl (4.6 kB)
Collecting opentelemetry-sdk
  Using cached opentelemetry_sdk-0.17b0-py3-none-any.whl (47 kB)
Installing collected packages: opentelemetry-api, wrapt, opentelemetry-sdk, opentelemetry-instrumentation, opentelemetry-distro
Successfully installed opentelemetry-api-0.17b0 opentelemetry-distro-0.17b0 opentelemetry-instrumentation-0.17b0 opentelemetry-sdk-0.17b0 wrapt-1.12.1
```

If I try to explicitly install api 1.0.0rc1 and instrumentation 0.17b0, pip complains and bails out:


```
 pip install opentelemetry-api==1.0.0rc1 opentelemetry-sdk==1.0.0rc1 opentelemetry-distro opentelemetry-instrumentation==0.17b0
Collecting opentelemetry-api==1.0.0rc1
  Using cached opentelemetry_api-1.0.0rc1-py3-none-any.whl (36 kB)
Collecting opentelemetry-sdk==1.0.0rc1
  Using cached opentelemetry_sdk-1.0.0rc1-py3-none-any.whl (35 kB)
Collecting opentelemetry-distro
  Using cached opentelemetry_distro-0.18b0-py3-none-any.whl (4.4 kB)
Collecting opentelemetry-instrumentation==0.17b0
  Using cached opentelemetry_instrumentation-0.17b0-py3-none-any.whl (15 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of opentelemetry-api to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install opentelemetry-api==1.0.0rc1 and opentelemetry-instrumentation==0.17b0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested opentelemetry-api==1.0.0rc1
    opentelemetry-instrumentation 0.17b0 depends on opentelemetry-api==0.17b0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

So it looks like if the instrumentations require opentelemetry-instrumentation==0.17b0 after the hotfix is released, they can't be used with 1.0.0rc1 API.


I think ideally we'd want to patch the code and release `0.18b1` as the hotfix version for opentelemetry-instrumentation and other instrumentation packages. If API needs a patch as well then I guess we'll need to release `1.0.0rc2` as the hotfix. 

Please let me know if I can help with the release or fixes in any way.

**Comment by lzchen** [comment]
@owais 
The other packages don't need a patch. The only thing that is needed is to bump the dependency version for `opentelemetry-instrumentation` to use `== 0.18b0`, which is already [released](https://pypi.org/project/opentelemetry-instrumentation/) and properly depends on `opentelemetry-api` v1.0.0rc1

**Comment by lzchen** [comment]
@owais Can you review again?

**Review by owais — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
