### PR TITLE
Fix requests intrumentation response hook type

### PR DESCRIPTION
**Pull request by ethervoid**
# Description

Response hook receives a third parameter, Response, and that should be reflected in the _ResponseHook type

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

We're using this instrumentation in our code and we've tested it in production

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by ocelotl** [comment]
@ethervoid please give us more information on the issue being fixed here. Please also add at least one test case for these changes.

**Comment by ethervoid** [comment]
@ocelotl Hi!, Basically is a missing type in the definition that is bringing errors when you have a type checker. I don't think we need tests, no change in functionality is involved

**Comment by ocelotl** [comment]
> @ocelotl Hi!, Basically is a missing type in the definition that is bringing errors when you have a type checker. I don't think we need tests, no change in functionality is involved


Please let us know what errors and what type checker

**Comment by ocelotl** [comment]
I'm not against this fix, but we could use a bit more information here regarding what the issue is.

**Pull request merged**
