### PR TITLE
Make Falcon  instrumentation compatible with Falcon >=3

### PR DESCRIPTION
**Pull request by adriangb**
Replace falcon.api.Request -> falcon.Request which exists on both Falcon 2 & 3

Steps to reproduce:

1. Install Falcon >=3: `pip install falcon==3.0.0`
2. Run the docs: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/falcon/falcon.html#usage

You'll get:

```
.../dist-packages/opentelemetry/instrumentation/falcon/__init__.py in <module>()
--> 129 _response_propagation_setter = FuncSetter(falcon.api.Response.append_header)
AttributeError: module 'falcon' has no attribute 'api'
```

And I verified that in Falcon >=3 `falcon.api` does not exit.

Also to note, `falcon.API` is being deprecated in favor of `falcon.App`. Not sure how you want to handle that. I reckon some version checks will be needed to support both Falcon 2 & 4.

### CODE REVIEW

**Comment by owais** [comment]
@adriangb Thanks for the PR. You'll also  need to update the supported Falcon versions here: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/d69fe1440225c2b908660d18c5381a94eb67f7db/instrumentation/opentelemetry-instrumentation-falcon/src/opentelemetry/instrumentation/falcon/package.py#L16

Also please sign the CLA and update the changelog.

**Comment by adriangb** [comment]
Thanks @owais . CLA link is giving me a 500, I opened a support ticket.

I edited the package and changelog. Will updating the package also run tests on 3.0?

**Comment by owais** [comment]
> I edited the package and changelog. Will updating the package also run tests on 3.0?

No. You'll need to update the test matrix in tox.ini to do that.

**Comment by adriangb** [comment]
@owais CLA issue is fixed and signed, and I updated `tox.ini`, although I couldn't test locally because as per #444 the `CONTRIBUTING.md` instructions are broken. Can you please kick off CI?

**Comment by owais** [comment]
It is triggered automatically on every push. Looks like the falcon tests are failing.

**Comment by adriangb** [comment]
> It is triggered automatically on every push.

Not if you're a first time contributor:

image

>  Looks like the falcon tests are failing.

I reverted the `tox.ini`, there were version conflicts in the env.

I'd appreciate a bit more hands-on support here, the interdependency between the otel packages (api, sdk, core, contrib, etc.) and the packaging of the repo (monorepo, tox, etc.) is a bit confusing for a first time contributor. Compounded with broken contributing instructions, it's taking a lot more work than I'd like to contribute a 1 line fix.

**Comment by adriangb** [comment]
@owais I saw you self assigned this. Will you be taking it over? I don't want us to duplicate work offline 😄

**Comment by owais** [comment]
@adriangb No, a PR assignee represents someone who has taken up the responsibility to review a PR and see it through. I don't intent to work on it :)

**Comment by adriangb** [comment]
Got it, thanks for clarifying. I'm going to pick this up again this week.

It does look like there's still some infrastructure / CI issues: I'm seeing failures in Celary tests and Linting timing out, which certainly aren't related to this change.

**Review by owais — APPROVED** [review]

**Comment by owais** [comment]
We should update tox.ini to test multiple versions but not a blocker for me rigth now.

**Comment by adriangb** [comment]
Yep I was just waiting to see if the current failures would resolve before changing more stuff. Looks like the last run passed, so I'll _try_ to put this change in again.

**Review by lonewolf3739 — APPROVED** [review]

**Pull request merged**
