### PR TITLE
redis: fix default port KeyError, wrong attr name

### PR DESCRIPTION
**Pull request by shlee322**
# Description
- fix default port KeyError
- wrong attr name (net.peer.ip -> net.peer.port)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by codeboten — APPROVED** [review]
Thanks for the fix @shlee322! Can you update the changelog

**Comment by lonewolf3739** [comment]
@shlee322 good catch, thanks. Can you also update the tests [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/tests/opentelemetry-docker-tests/tests/redis/test_redis_functional.py#L42) and [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/tests/opentelemetry-docker-tests/tests/redis/test_redis_functional.py#L135)

**Comment by codeboten** [comment]
@shlee322 looks like the docker-tests will need to be fixed as well before this PR can move forward.

**Comment by lzchen** [comment]
@shlee322 
Are you still working on this?

**Comment by shlee322** [comment]
@lzchen
Sorry. I'll fix it this week.

**Comment by lzchen** [comment]
@shlee322 
Is this still being worked on?

**Review by lzchen — APPROVED** [review]

**Comment by codeboten** [comment]
Thanks for the contribution @shlee322, I updated the tests for docker and found another issue to fix at the same time!

**Pull request merged**
