### PR TITLE
Fix fastapi version

### LINKED ISSUE #1663: Fix fastapi version
CI in `main` is failing right now because of `opentelemetery-instrumentation-fastapi` failures, fix `fastapi` version.

### PR DESCRIPTION
**Pull request by ocelotl**
Fixes #1663

### CODE REVIEW

**Comment by shalevr** [comment]
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/3bcc9fb5173600572479edae1c3071aa4bce6ee1/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/package.py#L16

Does this need to be updated too?

**Review by srikanthccv — COMMENTED** [review]
I am not sure about fixing the version. Looking at the CI failures, it's just the `test_uninstrument_app` failing, and after reading the CHANGELOG https://github.com/tiangolo/fastapi/releases/tag/0.91.0. Can we update the failing test instead?

**Comment by ocelotl** [comment]
> I am not sure about fixing the version. Looking at the CI failures, it's just the `test_uninstrument_app` failing, and after reading the CHANGELOG https://github.com/tiangolo/fastapi/releases/tag/0.91.0. Can we update the failing test instead?

Sure, but better to do that in other PR, right now this is stopping a regression fix in #1660 from entering into `main`.

**Comment by ocelotl** [comment]
> https://github.com/open-telemetry/opentelemetry-python-contrib/blob/3bcc9fb5173600572479edae1c3071aa4bce6ee1/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/package.py#L16
> 
> Does this need to be updated too?

Right, fixed :v:

**Review by shalevr — APPROVED** [review]

**Comment by srikanthccv** [comment]
Created #1665 to fix it separately.

**Pull request merged**
