### PR TITLE
 add automation to close stale issues

### PR DESCRIPTION
**Pull request by codeboten**
Fixes https://github.com/open-telemetry/opentelemetry-python/issues/1618

### CODE REVIEW

**Review by lzchen — APPROVED** [review]

**Review by lonewolf3739 — APPROVED** [review]
Is it possible to have something similar to SkipChangelog for this?

**Comment by codeboten** [comment]
> Is it possible to have something similar to SkipChangelog for this?

@lonewolf3739 similar how?

**Comment by lonewolf3739** [comment]
It could be some label like _no-auto-close_ and issues with that label are skipped on this action run.

**Comment by codeboten** [comment]
> It could be some label like _no-auto-close_ and issues with that label are skipped on this action run.

Oh yeah, the `feature-request` label exempts it from being auto-closed:
https://github.com/open-telemetry/opentelemetry-python-contrib/pull/393/files#diff-221ec56332617dc2f33423aaada2c915da7a8a49d88ad5189606cfa78518fea9R15

**Pull request merged**
