### PR TITLE
Add note about Falcon version support

### PR DESCRIPTION
**Pull request by adriangb**
@owais I'm opening this partially so that I can get workflows to run on push and make my life easier in #607 . But also until #607 gets merged, this can't hurt to have 😄

### CODE REVIEW

**Review by owais — APPROVED** [review]
haha good hack :)

**Comment by adriangb** [comment]
😢 
Screen Shot 2021-08-03 at 4 47 36 PM

**Comment by adriangb** [comment]
I added another commit to kick things off again. Hopefully tox doesn't hang for 40 min again

**Comment by owais** [comment]
Ran the workflow again. Sorry about the terrible first experience. I'm thinking going back to Linux contribution of accepting patches via email might be better :)

I'll bring this up in our next SIG call and see if we can do anything to make it easier to contribute.

**Comment by adriangb** [comment]
No worries! It's nice that this is at least on GH/GHA. Just working instructions in CONTRIBUTING.md would go a long way.

**Comment by adriangb** [comment]
@owais looks like we're stuck again. tox has been running for hours (days?) with no output and without exiting 0 or 1

**Comment by ocelotl** [comment]
I am rerunning all the jobs, seems like several PRs are being stuck in CI and not only on this repo.

**Comment by adriangb** [comment]
@ocelotl can you kick these off again? Last time the tests just timed out. I also merged master into this branch fwiw.

**Comment by ocelotl** [comment]
> @ocelotl can you kick these off again? Last time the tests just timed out. I also merged master into this branch fwiw.

Sure, I have started them again. It is very likely that they will get stuck again :disappointed: 

I have filed an issue with Github [here](https://github.com/actions/virtual-environments/issues/3869).

**Comment by adriangb** [comment]
@lzchen something went wrong with your merge in e0243aa: 40ab25a is passing all tests, and also this PR is just a doc so it should never fail tests.

**Pull request merged**
