### PR TITLE
Fix exception handling for events with requestContext

### LINKED ISSUE #2399: AWS Lambda/APIGW unhandled exception causes UnboundLocalError
**Describe your environment** 
AWS Lambda, python3.12, using [opentelemetry-lambda layer python 0.5](https://github.com/open-telemetry/opentelemetry-lambda/releases/tag/layer-python%2F0.5.0 the arn:aws:lambda:us-east-1:184161586896:layer:opentelemetry-python-0_5_0:1) which includes opentelemetry-python [1.23.0/0.44b0] 

**Steps to reproduce**
A lambda function invoked with APIGW, with auto-instrumentation, after an unhandled exception causes:
```
[ERROR] UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/python/wrapt/wrappers.py", line 598, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/opt/python/opentelemetry/instrumentation/aws_lambda/__init__.py", line 378, in _instrumented_lambda_handler_call
    if isinstance(result, dict) and result.get("statusCode"):
    ^^^^^^
```

This can be reproduced with this code:
```python
import json
import random
import logging

from opentelemetry import trace

tracer = trace.get_tracer_provider().get_tracer(__name__)
logger = logging.getLogger()


def lambda_handler(event, context):
    if random.random() < 0.1:  # 10% chance to raise an error
        raise Exception('Injected error')
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
        }),
    }
```

**What is the expected behavior?**
The original exception is propagated (and not the `UnboundLocalError`)

**What is the actual behavior?**
The original exception is not propagated but this exception is raised instead:
```
[ERROR] UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/python/wrapt/wrappers.py", line 598, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/opt/python/opentelemetry/instrumentation/aws_lambda/__init__.py", line 378, in _instrumented_lambda_handler_call
    if isinstance(result, dict) and result.get("statusCode"):
    ^^^^^^
```

**Additional context**
It seems that it would be enough to declare `result` at the beginning of this [block of code](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/fdcbbddb6c753e5e9d494ba399a5b4bcab4afc3f/instrumentation/opentelemetry-instrumentation-aws-lambda/src/opentelemetry/instrumentation/aws_lambda/__init__.py#L367-L392):

```python
    result = None  # Assign a default value to result
    exception = None
            try:
                result = call_wrapped(*args, **kwargs)
            except Exception as exc:  # pylint: disable=W0703
                exception = exc
                span.set_status(Status(StatusCode.ERROR))
                span.record_exception(exception)

            if isinstance(lambda_event, dict) and lambda_event.get(
                "requestContext"
            ):
                span.set_attribute(SpanAttributes.FAAS_TRIGGER, "http")

                if lambda_event.get("version") == "2.0":
                    _set_api_gateway_v2_proxy_attributes(lambda_event, span)
                else:
                    _set_api_gateway_v1_proxy_attributes(lambda_event, span)

                if isinstance(result, dict) and result.get("statusCode"):
                    span.set_attribute(
                        SpanAttributes.HTTP_STATUS_CODE,
                        result.get("statusCode"),
                    )
```

### PR DESCRIPTION
**Pull request by alessandrobologna**
# Description

For Lambda invocations with an event that contains a `requestContext` property, the current code throws an `UnboundLocalError` if an exception (of other type) is thrown in the function execution, due to the `result` variable being accessed before being initialized. This PR simply makes sure that is initialized before being used.

Fixes #2399 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] ran `tox -e py38-test-instrumentation-aws-lambda`
- [x] ran `tox -e py39-test-instrumentation-aws-lambda`
- [x] ran `tox -e py310-test-instrumentation-aws-lambda`
- [x] ran `tox -e py311-test-instrumentation-aws-lambda`

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by xrmx — APPROVED** [review]
Thanks, nice catch!

**Review by lzchen — APPROVED** [review]

**Comment by lzchen** [comment]
@alessandrobologna 

Please add a CHANGELOG entry.

**Comment by alessandrobologna** [comment]
Added CHANGELOG entry.

**Review by xrmx — APPROVED** [review]

**Review by xrmx — CHANGES_REQUESTED** [review]
@alessandrobologna you added more changelog entries than this PR :sweat_smile:

**Comment by alessandrobologna** [comment]
@xrmx apologies, this should be fixed now

**Review by ocelotl — APPROVED** [review]

**Comment by jamesrwhite** [comment]
👋  Hey, we've just run into this issue. Is it possible a new release can be made soon that includes this fix?

**Pull request merged**
