### PR TITLE
[opentelemetry-instrumentation-httpx] fix mixing of sync and non async hooks

### LINKED ISSUE #1201: HTTPXClientInstrumentor mixes async and non async hooks
**Describe your environment** 
Python 3.10.3
opentelemetry-api==1.12.0rc2
opentelemetry-sdk==1.12.0rc2
opentelemetry-instrumentation-httpx==0.32b0

**Steps to reproduce**
Run this example:
```
 from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor
 import httpx, asyncio

 def httpx_request_hook(span, request):
     print("test")

 HTTPXClientInstrumentor().instrument(request_hook=httpx_request_hook)

 # This succeeds
 with httpx.Client() as client:
     client.get("http://example.com")

 async def test_func():
     async with httpx.AsyncClient() as client:
         await client.get("http://example.com")

 # this fails with `TypeError: object NoneType can't be used in 'await' expression`
 asyncio.run(test_func())
```

**What is the expected behavior?**
After instrumentation it should be possible to successfully use httpx in both sync and async contexts.

**What is the actual behavior?**
If a non-async hook is provided then an exception is raised when the AsyncClient is used. If an async hook is provided then it never executes when the non-async Client is used.

**Additional context**
It seems to me this should either allow both async and sync hooks to be provided separately. Or it should require that the hook be non-blocking and only support non-async hooks.

### PR DESCRIPTION
**Pull request by samypr100**
# Description

Currently when using request/response hooks with `HTTPXClientInstrumentor().instrument()`, the hooks are used for both `httpx.Client` and `httpx.AsyncClient`. This becomes an issue if you have a codebase that uses both since the hooks are awaited when using `httpx.AsyncClient` and not awaited when using `httpx.Client`.

This PR introduces the ability to pass dedicated sync and async hooks to the main `instrument()` call.

For example
```diff
-HTTPXClientInstrumentor().instrument(request_hook=request_hook, response_hook=response_hook)
+HTTPXClientInstrumentor().instrument(request_hook=request_hook, response_hook=response_hook, async_request_hook=async_request_hook, async_response_hook=async_response_hook)
```

Other signatures such as `instrument_client` are left as-is as this particular situation doesn't quite apply the same way.

I added a fallback to using the `request_hook/response_hook` when `async_request_hook/async_response_hook` is not specified, that way it won't break any code. Current tests will verify this inherently. Lastly, I slighly adjusted some of the existing typing as a result of these changes to make it more clear which hook(s) are applicable.

Fixes #1201

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Ran `tox` to test `test-instrumentation-httpx`

# Does This PR Require a Core Repo Change?

- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by macieyng** [comment]
@srikanthccv Can you please review it 🙏

**Review by ocelotl — APPROVED** [review]

**Comment by samypr100** [comment]
@ocelotl Thanks for the review.

There seems to be an unrelated error on the GHA side:

`ImportError: cannot import name 'url_quote' from 'werkzeug.urls'` causing `py310-test-instrumentation-flask213` to fail.

**Comment by ocelotl** [comment]
> @ocelotl Thanks for the review.
> 
> There seems to be an unrelated error on the GHA side with flask.
> 
> `ImportError: cannot import name 'url_quote' from 'werkzeug.urls'` causing `py310-test-instrumentation-flask213` to fail.

Yes, apparently it is related to the recent release of Werkzeug 3.0.0, I'll take care of this issue.

**Comment by samypr100** [comment]
@ocelotl Merge conflicts have been fixed

**Comment by samypr100** [comment]
@ocelotl Merge conflicts with CHANGELOG should be fixed again

**Comment by samypr100** [comment]
@ocelotl Following up 😅 , can workflows be re-triggered?  🙏

**Comment by samypr100** [comment]
@ocelotl Merge conflicts with CHANGELOG have been fixed

**Pull request merged**
