### PR TITLE
Extending SQLCommenter support of dbapi into psycopg2

### PR DESCRIPTION
**Pull request by Thiyagu55**
# Description

This PR integrates SQLCommenter into Psycopg2. When SQLCommenter is enabled in the library the SQL query logs will have traceparent id appended.

It's enabled using flag enable_commenter
`Psycopg2Instrumentor()._instrument(tracer_provider=provider, enable_commenter=True)`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] tox -e  py39-test-instrumentation-psycopg2
- [X] tox -e docker-tests                                         

# Does This PR Require a Core Repo Change?

- [X] Yes. - Link to [PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/941): 

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [X] Changelogs have been updated
- [X] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by srikanthccv — COMMENTED** [review]
@Thiyagu55 Can you add a test for this

**Comment by Thiyagu55** [comment]
> @Thiyagu55 Can you add a test for this

1. It's just an extension of dbapi as this PR involves only passing enable_commenter param
2. We can't add test for mock connection

**Comment by ocelotl** [comment]
> > @Thiyagu55 Can you add a test for this
> > @srikanthccv
> 
> 1. It's just an extension of dbapi as this PR involves only passing enable_commenter param
> 2. We can't add test for mock connection

A test case for this change can be very simple, making sure the default value is `False`, that passing `enable_commenter` is read into `kwargs`, etc.

**Comment by srikanthccv** [comment]
And you can add some integration tests [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/tests/opentelemetry-docker-tests/tests/postgres/test_psycopg_functional.py#L155) enabling this feature.

**Comment by Thiyagu55** [comment]
> And you can add some integration tests [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/tests/opentelemetry-docker-tests/tests/postgres/test_psycopg_functional.py#L155) enabling this feature.

@srikanthccv @ocelotl Unit tests and integration tests have been added and PR description is updated

**Comment by srikanthccv** [comment]
@Thiyagu55 Please fix the failing tests

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
