### PR TITLE
elasticsearch: stop testing on ancient versions

### PR DESCRIPTION
**Pull request by xrmx**
# Description

Pick 6.0 as the baseline. Elasticsearch 2 client was EOL in 2018, Elasticsearch 5 in 2019.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] tox

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by xrmx** [comment]
Looking at the stats there are still 100K downloads a month for elasticsearch5, may just drop just 2. Still there are not have been releases since 2019.

**Comment by xrmx** [comment]
> Looking at the stats there are still 100K downloads a month for elasticsearch5, may just drop just 2. Still there are not have been releases since 2019.

5 has been EOL since 2019 though, probably not many people using opentelemetry with it.

**Comment by tammy-baylis-swi** [comment]
> 5 has been EOL since 2019 though, probably not many people using opentelemetry with it.

I think it's fair to drop 5 support, then also add a changelog entry under `Breaking changes` subheader.

**Comment by xrmx** [comment]
> > 5 has been EOL since 2019 though, probably not many people using opentelemetry with it.
> 
> I think it's fair to drop 5 support, then also add a changelog entry under `Breaking changes` subheader.

Done

**Review by ocelotl — APPROVED** [review]

**Comment by xrmx** [comment]
@ocelotl I have in the pipeline testing for newer elasticsearch version so the version is useful to keep

**Comment by ocelotl** [comment]
> @ocelotl I have in the pipeline testing for newer elasticsearch versions so the version is useful to keep

We are no longer using package versions in the naming of test requirements files, if more testing is added for elasticsearch that uses different versions, the test requirements files are numbered from `0` onwards.

**Comment by xrmx** [comment]
> > @ocelotl I have in the pipeline testing for newer elasticsearch versions so the version is useful to keep
> 
> We are no longer using package versions in the naming of test requirements files, if more testing is added for elasticsearch that uses different versions, the test requirements files are numbered from `0` onwards.

AFAIR there was agreement that reinstating the more semantic versioning after your PRs reworking tests was fine.

**Pull request merged**
