### PR TITLE
fix: Update falcon instrumentation to follow semantic conventions

### LINKED ISSUE #1726: Improve Falcon OpenTelemetry Instrumentation for Hug Web Framework
**Is your feature request related to a problem?**
We are extensively using the [Hug](https://hugapi.github.io/hug/) web framework in our organization. Since Hug is built on top of Falcon, we have been using the `falcon-instrumentation` library to instrument our applications. However, this approach results in spans that are difficult to interpret, as shown in the screenshot below: 

Screen Shot 2023-03-22 at 11 03 16

**Describe the solution you'd like**
We believe that better instrumentation support for Hug can be achieved through one of the following options:
- Develop a dedicated `hug-instrumentation` library, which would be largely similar (about 90%) to the existing falcon-instrumentation .
- Create a `hug-instrumentation` library that depends on falcon-instrumentation and overrides some functions. However, this solution might be less maintainable and less readable.
- Introduce a configuration option in the `falcon-instrumentation` library that enhances its compatibility with Hug.

**Additional context**
I have not personally tried the Falcon framework to see how spans are named there, but I assume they are similar to those of other frameworks. I would appreciate any input from project contributors on this matter and am willing to explore the issue further. What are your thoughts on the best approach to improve OpenTelemetry instrumentation for the Hug web framework?

### PR DESCRIPTION
**Pull request by Nek0trkstr**
# Description

Falcon instrumentation was using route name plus method (Router.on_get) as span name which does not follow semantic conventions as stated #1726. 

Fixes #1726 

## Type of change
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Instrument any falcon application with version <= 0.39b0. Span names would not follow semantic conventions.
Added unit tests for low-cardinality route and changed previous tests that enforce incorrect span names.

# Does This PR Require a Core Repo Change?
- [x] No.

# Checklist:

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by Nek0trkstr** [comment]
Hi may somebody please take a look why [build (pypy3, instrumentation, ubuntu-20.04)](https://github.com/Nek0trkstr/opentelemetry-python-contrib/actions/runs/5079304961/jobs/9146135606#logs) is timing out after 6 hours, on `test_urllib3_ip_support.py::TestURLLib3InstrumentorWithRealSocket::test_basic_http_success_using_connection_pool`

This is the end of the log where job is stuck.
```
test_urllib3_ip_support.py::TestURLLib3InstrumentorWithRealSocket::test_basic_http_success_using_connection_pool 
-------------------------------- live log call ---------------------------------
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1:38559', port=None): Read timed out. (read timeout=3)")': /status/200
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1:38559', port=None): Read timed out. (read timeout=3)")': /status/200
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1:38559', port=None): Read timed out. (read timeout=3)")': /status/200
```

My change is not affecting `URLLib3Instrumentor` so I wonder why is it happening.

**Comment by srikanthccv** [comment]
It's unrelated to your changes so you can ignore them. I think this PR https://github.com/open-telemetry/opentelemetry-python/pull/3318 by @shalevr might fix it.

**Comment by Nek0trkstr** [comment]
Hi, @srikanthccv and @shalevr . 
I see that #3318 was not merged yet. Do we have a way to workaround this timeout issue?

**Comment by shalevr** [comment]
> Hi, @srikanthccv and @shalevr . I see that #3318 was not merged yet. Do we have a way to workaround this timeout issue?

The timeout issue is fixed now, but there is a new blocker with celery tests

**Review by srikanthccv — APPROVED** [review]

**Review by shalevr — APPROVED** [review]

**Pull request merged**
