### PR TITLE
Support aio_pika 9

### PR DESCRIPTION
**Pull request by phillipuniverse**
# Description

Support aio_pika 9 as a fast-follow to aio_pika 8 support added at  #1481.

[aio_pika 9 release notes](https://github.com/mosquito/aio-pika/releases)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Repo tests

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by phillipuniverse** [comment]
@ofek1weiss FYI

@srikanthccv think we can get this into the release this week?

**Comment by ofek1weiss** [comment]
Looks like in tox.ini you typed aio-pika8 instead of 9

**Comment by phillipuniverse** [comment]
@ofek1weiss things should be good now, aio-pika 9 moved around the version information. Solution tested with 7, 8 and 9 and looks good.

**Comment by ofek1weiss** [comment]
Looks good to me 👍

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
