### PR TITLE
revert: feat(instrumentation/asgi): add target to metrics

### PR DESCRIPTION
**Pull request by sk-**
Unfortunately I made a mistake in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1323 where I assumed that the scope was laready being processed by the framework at the moment of reporting, but of course that's not true as the framework has not even seen the request at that point.

Is for that reason that we are not able to extract any route information in the middleware to report what the target is.

Sorry for the noise, and be happy to help if anyone has any idea how we could fix this.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by sk-** [comment]
@srikanthccv could you please take a look

**Comment by srikanthccv** [comment]
This is not breaking anything, right? It's just that target is not collected. I am not super familiar with this instrumentation, but if it's not breaking anything, we can spend some time and get the correct fix merged instead of reverting it.

**Comment by sk-** [comment]
@srikanthccv sounds good, I think I have found the way to fix it. Thanks for suggesting it. Will send a PR for that shortly.

**Comment by ocelotl** [comment]
> t able to extract any route information in the middleware to report

@sk Is this PR still needed? If not please close it.

**Comment by sk-** [comment]
I think i have found a way to fix it, so closing it for now.

**Comment by gabrielqs** [comment]
was there ever a way to achieve this? i'm looking at span metrics emitted by the last version of the fastapi autoinstrumentation and i don't see the `http.route` attribute in them, even though this code is present in the otel sdk. maybe there's a way we could apply to have that attribute populate span metrics by using a custom span/metric processor?

**Comment by sk-** [comment]
Yes, this is working and being used in production. However, this was added for the asgi plugin, not sure how the fastapi plugin works.

Also note, that this was added some time ago, when the semantic conversions specified the attribute name was `http.target`, not `http.route`.

**Pull request closed without merging**
