### PR TITLE
Update Doc for aws propagator default sampling behavior

### PR DESCRIPTION
**Pull request by willarmiros**
# Description

Dupe of #656, for also testing CODEOWNERS

### CODE REVIEW

**Review by owais — APPROVED** [review]

**Review by NathanielRN — APPROVED** [review]

**Comment by NathanielRN** [comment]
Hm interesting, maybe because I am part of the commit history I didn't get set a reviewer even though I am a CODEOWNER? But I can still give an approving review?

**Comment by owais** [comment]
May be. I think we should update the check so that it is only required when the author is not a code-owner.

**Comment by NathanielRN** [comment]
Also it looks like [the "Component Owners" test](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/658/checks?check_run_id=3500599381) is failing 😕 @lzchen 

```
Run dyladan/component-owners@main
  with:
    assign-owners: true
    request-owner-reviews: true
    repo-token: ***
    config-file: .github/component_owners.yml
1 owners found NathanielRN
Adding assignees
Error: Resource not accessible by integration
```

**Comment by willarmiros** [comment]
Yeah sorry, totally didn't think of that when giving you the co-author @NathanielRN

**Comment by NathanielRN** [comment]
No worries at all @willarmiros ! I think it's useful to see what this action does. We know the CODEOWNER works and the test passes from #657, but we should figure out the change in this PR.

@lzchen had a good idea that this is because it's from your fork wheras #657 was from an upstream branch. I remember seeing the `Error: Resource not accessible by integration` a lot such as [in this GitHub Issue](https://github.com/actions/first-interaction/issues/10#issuecomment-545576314) when doing operations on the repo.

**Review by codeboten — APPROVED** [review]

**Comment by NathanielRN** [comment]
Closing in favor of #656 now that we checked the CODEOWNERs tool is working as expected.

**Comment by codeboten** [comment]
> Closing in favor of #656 now that we checked the CODEOWNERs tool is working as expected.

I... this was really confusing. The file diff made it look like this was being added in a different place lol

**Comment by NathanielRN** [comment]
> I... this was really confusing. The file diff made it look like this was being added in a different place lol

Ah really sorry about that! Testing CODEOWNERs got in the middle of me deciding the change would fit better at a different point in the docs 😓 I really appreciate your green check mark! Especially since it helped me realize I should've closed this one immediately once #656 got merged but better late than never I guess 😅

**Pull request closed without merging**
