### PR TITLE
Sync with Remove time_ns from API

### LINKED ISSUE #332: Sync with No real nanosecond resolution provided by time_ns
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**
What did you see instead?

**Additional context**

### PR DESCRIPTION
**Pull request by ocelotl**
# Description

Update contrib modules so that they match with the changes added [here](https://github.com/open-telemetry/opentelemetry-python/pull/1602).

Fixes #332
## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [X] Yes. - Link to PR: https://github.com/open-telemetry/opentelemetry-python/pull/1602
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by owais — APPROVED** [review]
LGTM. Thanks

**Review by owais — CHANGES_REQUESTED** [review]
Just looked at the other PR. IMO we should just mark the function as internal/private instead of monkey patching `time` module.

**Comment by codeboten** [comment]
@toumorokoshi any thoughts on the warning as it is now or alternate recommendations?

**Comment by toumorokoshi** [comment]
> @toumorokoshi any thoughts on the warning as it is now or alternate recommendations?

I [left a comment](https://github.com/open-telemetry/opentelemetry-python/pull/1602#discussion_r588073747) but also approved the PR in the name of velocity.

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
@owais it looks like your change request has been addressed, can you confirm.

**Review by owais — APPROVED** [review]

**Pull request merged**
