### PR TITLE
adding unit test case for ASGI framework for application wrapped with…

### PR DESCRIPTION
**Pull request by sanketmehta28**
# Description
This PR includes a unit test case for [PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/843/)  
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
- [ ] Test A: Ran the full pytest for asgi framwork

# Does This PR Require a Core Repo Change?
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Unit tests have been added

### CODE REVIEW

**Comment by sanketmehta28** [comment]
HI, Can we skip the changelog for this PR? I have added the unit test missed in [PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/843)

**Comment by ocelotl** [comment]
Looks good, please read the logs of the generate test case :v:

**Comment by sanketmehta28** [comment]
> 

Where do I read the logs?

**Comment by sanketmehta28** [comment]
@ocelotl : done and committed the changes

**Review by lzchen — APPROVED** [review]

**Review by ocelotl — APPROVED** [review]

**Pull request merged**
