### PR TITLE
fix NonRecordSpan.attributes access

### PR DESCRIPTION
**Pull request by adriangb**
I'm seeing this fail in my test suite:

```python
            duration_attrs[
                SpanAttributes.HTTP_STATUS_CODE
>           ] = span.attributes.get(SpanAttributes.HTTP_STATUS_CODE)
E           AttributeError: 'NonRecordingSpan' object has no attribute 'attributes'
```

And I can tell that `NotRecordingSpan` does not have `attributes` and it seems like that would be checked for. I tried to add a test but with all of the mocking  and lack of typing I can't tell what is actually being tested where.

### CODE REVIEW

**Comment by adriangb** [comment]
Seems like this was added in #1230, any thoughts @TheAnshul756?

**Comment by srikanthccv** [comment]
You are correct, this throws an error in the absence of SDK. Please use `span.is_recording()` instead.

**Comment by adriangb** [comment]
I tried that locally and it made some other test fail, we'll see what CI says

**Comment by TheAnshul756** [comment]
Looks like the issue is in the tests. 'span.is_recording()' is false in case of the failed tests. I'm looking into it.

**Comment by TheAnshul756** [comment]
Hello @adriangb 
I've added the fix and want to commit. So should I create a PR on your fork?

**Comment by TheAnshul756** [comment]
Please merge [this PR](https://github.com/adriangb/opentelemetry-python-contrib/pull/1)?

**Comment by adriangb** [comment]
> Please merge [this PR](https://github.com/adriangb/opentelemetry-python-contrib/pull/1).

Done

**Comment by adriangb** [comment]
Hi is there anything missing to push this forward?

**Review by TheAnshul756 — APPROVED** [review]

**Pull request merged**
