### PR TITLE
add option to disable asgi intern trace

### PR DESCRIPTION
**Pull request by raphaelauv**
# Description

Add an option to disable intern trace of the asgi instrumentation

Fixes https://github.com/open-telemetry/opentelemetry-python-contrib/issues/831

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by owais** [comment]
@raphaelauv could you please add some explanation about this or create an issue? It would be nice to know what problem this solves or why having those spans can be a problem in the first place. Normally a custom processor/exporter or Otel collector should be used to drop specific spans.

**Comment by raphaelauv** [comment]
The current ASGI instrumentation produce 3 spans :

Screenshot from 2021-12-30 13-44-17

So I was proposing to add an option to disable the two internal spans. Like ask with this issue -> #831

`custom processor/exporter or Otel collector should be used to drop specific spans.`

never heard about that before , do you have any example ? Thank you

**Comment by owais** [comment]
Thanks. Yes, I understand you'd like to disable generation of the two spans but what I'm trying to understand is why those spans are a problem in the first place?

**Comment by raphaelauv** [comment]
` why those spans are a problem in the first place?`
I do not need them and I propose to add an option to disable theses internal spans.

**Comment by lzchen** [comment]
@raphaelauv 
Is it possible to create a custom sampler that drop spans based off of `name` or `kind`? You can also create a custom span processor that drops the spans that you don't need.

**Comment by shwetasah-cape** [comment]
> @raphaelauv Is it possible to create a custom sampler that drop spans based off of `name` or `kind`? You can also create a custom span processor that drops the spans that you don't need.

I am trying to create a custom span processor by overriding the `on_end` method in SpanProcessor, but it doesn't seem to be dropping the span. Is there any example in the docs for a customSpanProcessor to drop spans or prevent them from being exported?

```
class SpanDroppingProcessor(SpanProcessor):
    def on_end(self, span: ReadableSpan) -> None:
        if span.kind == SpanKind.INTERNAL and span.attributes.get("type") == "http.response.body":
            return
```

**Comment by bsmedberg-xometry** [comment]
@shwetasah-cape did you ever come across a solution to suppress these spans? Context for our organization is that for larger requests or responses, we are sometimes seeing dozens or more little "send" and "receive" spans coming from the ASGI integration, and this is causing is cost+load issues in our opentelemetry collector for little actual value, so I'd like to ASAP figure out a way to suppress these at the application level before they get to our collector.

**Comment by shwetasah-cape** [comment]
I am sorry I couldn't figure out how to suppress them. We too have the exact same context as yours.

**Pull request closed without merging**
