### PR TITLE
Update datadog exporter error tagging

### LINKED ISSUE #244: Datadog exporter shouldn't parse span description to determine if there was an exception
The Datadog exporter currently [parses the status description](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/exporter.py#L252) to determine if an exception was raised, yet [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#record-exception) requires these to be recorded as events (and [the python code already does this](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L690-L715)), so the Datadog exporter should read this data from the event list instead of hoping the description is properly formatted.

The current code does say that [span events are not supported ](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/exporter.py#L252), and while that would suggest that *reporting* events are not supported, we could certainly parse them for this data.

I'll probably tackle this, I'm already working on #154.  Also mentioned in #236, where I worked around the current behavior.

### PR DESCRIPTION
**Pull request by ericmustin**
# Description

Fixes #244(https://github.com/open-telemetry/opentelemetry-python-contrib/issues/244). I think this is ready for review, pretty straightforward, when span status is not `ok` we iterate over events and look for exception info.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Updated Unit Tests

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by ericmustin** [comment]
cc @majorgreys @alertedsnake @codeboten reviews welcome! cheers

**Review by majorgreys — COMMENTED** [review]
Is the existing test sufficient to test the new event exception extraction?

**Comment by majorgreys** [comment]
@ericmustin Thanks! Can a test be added for the fallback? Is there any scenario where this fallback is necessary?

**Comment by ericmustin** [comment]
@majorgreys yea im not sure, i think let's just remove the old fallback approach, in practice we should never need it now

**Review by alertedsnake — APPROVED** [review]
This looks great, thanks @ericmustin!  I'm glad you got a chance to work on it before I could :)

**Comment by lzchen** [comment]
@majorgreys 
Have your questions been answered?

**Review by majorgreys — APPROVED** [review]

**Review by lzchen — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
