### PR TITLE
Update README.rst - Add monthly downloads badge

### PR DESCRIPTION
**Pull request by ayushjain01**
# Description

This PR adds a monthly downloads badge to the readme file. View more at - https://piptrends.com/widgets/opentelemetry-instrumentation-pyramid and https://piptrends.com/package/opentelemetry-instrumentation-pyramid
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [X] Documentation has been updated

### CODE REVIEW

**Comment by emdneto** [comment]
Thanks @ayushjain01 . You need to sign the CLA to get this reviewed and merged. See https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#sign-the-cla

**Comment by ixmatus** [comment]
@emdneto a colleague of this person tried to open this exact PR against a project I'm the maintainer for as well (https://github.com/ixmatus/inflector/pull/16). This is a promotional campaign and they (or colleagues) appear to be doing it on reddit too, I think this is suspicious activity. They are creating an external dependency on a web property that (as far as I can tell) is not officially blessed by pypi. I recommend rejecting this PR.

Users can get package statistics from `libraries.io` which is linked to directly by pypi itself.

**Comment by emdneto** [comment]
@open-telemetry/python-approvers to reject this. @ixmatus is right. I looked at the user's GitHub profile, and he has the same PR against several repos with that change, and in all of the repos, maintainers are rejecting the PR. I think we should do the same.

**Comment by xrmx** [comment]
Closing then, if we want badges we can use shields.io like the rest of the projects

**Pull request closed without merging**
