### PR TITLE
Support confluent kafka

### PR DESCRIPTION
**Pull request by oxeye-dorkolog**
# Description

This PR impelements instrumentation for confluent-kafka client. it heavily relies on [PR-905](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/905). It creates proxy objects for `cimpi.Producer` and `cimpl.Consumer` and patch their methods using wrapt

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] Deployed confluent-kafka producer/consumer with manual and auto instrumentation

# Does This PR Require a Core Repo Change?

- [X] No.

# Checklist:

- [X] Followed the style guidelines of this project
- [X] Changelogs have been updated
- [X] Unit tests have been added
- [X] Documentation has been updated

### CODE REVIEW

**Comment by Sahadar** [comment]
Hello,
Please don't forget to place it in PyPI - currently its still not available to install:
https://pypi.org/search/?q=opentelemetry-instrumentation-confluent-kafka&o=

**Comment by srikanthccv** [comment]
@Sahadar We didn't forget. It's just not released yet. It should be available on pypi from next release.

**Comment by lzchen** [comment]
@oxeye-dorkolog 
Please add yourself to [component owners](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/.github/component_owners.yml) for this package.

**Comment by oxeye-dorkolog** [comment]
@lzchen already did as part of the PR

**Pull request merged**
