### PR TITLE
Added helper script to run multiple tox environments

### PR DESCRIPTION
**Pull request by antonpirker**
# Description

This adds a simple helper script `./scripts/runtox.sh` that allows people to run multiple `tox` environments with one call.

So `./scripts/runtox.sh py312` will run all tox environments having the string `"py312"` in their name. 

This is helpful if you want to run all tox environments in one Python version, or run one environment in all Python versions. (like this: `./scripts/runtox.sh fastapi`)

Contributed the same thing in `opentelementry-python`: 
https://github.com/open-telemetry/opentelemetry-python/pull/4095

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Ran it locally and it works (also we have something similar in Sentry, so I just copied it over)

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by ocelotl** [comment]
You can do the same with `tox -f 312`. I am curious about the motivation behind this PR, in which scenario did you want to run all tests for a particular python version?

**Comment by xrmx** [comment]
> You can do the same with `tox -f 312`. I am curious about the motivation behind this PR, in which scenario did you want to run all tests for a particular python version?

I guess when adding support for a new python version

**Comment by lzchen** [comment]
> I guess when adding support for a new python version

This most of the time is done during implementation and in that case the existing build will detect errors for you. Not sure if that warrants a new tox helper script :|

**Comment by xrmx** [comment]
> > I guess when adding support for a new python version
> 
> This most of the time is done during implementation and in that case the existing build will detect errors for you. Not sure if that warrants a new tox helper script :|

**Comment by antonpirker** [comment]
Yes, my motivation was to easily run multiple environments at once, but as `tox` can do this (which I did not know) (see this comment here: https://github.com/open-telemetry/opentelemetry-python/pull/4095#pullrequestreview-2210520930) 

This PR is useless. Will close it. Sorry for the noise!

**Pull request closed without merging**
