### PR TITLE
Using importlib_metadata for entry points instead of pkg_resources

### LINKED ISSUE #1970: Opentelemetry instrumentation uses deprecated pkg_resources.
**Describe your environment** 
Python 3.11
Setuptools >= 67.5.0
Windows 11

**Steps to reproduce**

Any operation that imports opentelemetry\instrumentation\dependencies.py

**What is the expected behavior?**

No deprecation warnings

**What is the actual behavior?**
What did you see instead?

`C:\Users\jenielse\Miniconda3\envs\myenv\Lib\site-packages\opentelemetry\instrumentation\dependencies.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html`

**Additional context**

This was removed from opentelemetry sdk/api in https://github.com/open-telemetry/opentelemetry-python/pull/3047

In addition to being deprecated pkg_resources is known to be problematic since it indexes all packages on start up adding significant overhead to the package import. Normally this should be replaced by importlib.resources or for older python version support importlib_resources  

As a bonus this will also remove the runtime dependency on setuptools

### PR DESCRIPTION
**Pull request by jeremydvoss**
# Description

pkg_resources is deprecated. Following example of https://github.com/open-telemetry/opentelemetry-python/pull/3217/files

Helps to fix #1970

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Existing tests

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by pcorpet** [comment]
Any chance to see this PR moving forward please? Can I help in some ways?

**Comment by pcorpet** [comment]
@jeremydvoss can I help you finalize this PR?

**Comment by multani** [comment]
@jeremydvoss Do you have any plan with this change? It would be great if these warnings get fixed! :bow:

**Comment by Olegt0rr** [comment]
@jeremydvoss, do need any help with this PR? 
Please, don't abandon it :(

**Comment by multani** [comment]
It has been several months already without any updates. I will try to propose a new change on top of this one I the coming days, with updated code to fix all the warnings.

**Comment by multani** [comment]
Actually, it's already picked up in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2181/

**Pull request closed without merging**
