### PR TITLE
Remove erroneous `type` attribute from asgi instrumentation

### LINKED ISSUE #2055: ASGI instrumentation creates a 'type' attribute
See https://github.com/open-telemetry/opentelemetry-python-contrib/blob/7166de673fa9dd7abc178bec3103d4adebb05e0d/instrumentation/opentelemetry-instrumentation-asgi/src/opentelemetry/instrumentation/asgi/__init__.py#L681

This results in an attribute like `{'type': 'http.request.body'}`, which seems wrong. `type` is a _super_ generic key and I don't think leaking the details of the web framework spec (`http.request.body` is an ASGI specific string) is very helpful to users.

Can we get rid of this?

### PR DESCRIPTION
**Pull request by samuelcolvin**
# Description

As per https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2055#issuecomment-1918148101 this PR removes the undocumented and non-specific attribute `type` from `opentelemetry-instrumentation-asgi`.

Fixes #2055

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] none so far...

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by samuelcolvin** [comment]
I'd also be happy to change this to use a [semconv HTTP attribute](https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/), but I couldn't see one that would be appropriate.

**Review by srikanthccv — APPROVED** [review]

**Review by shalevr — COMMENTED** [review]
Could you remove the type attribute from the tests?
in the test_asgi_middleware.py file
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/6c13a5eddce4c8446805759bf099a3e79dcd9083/instrumentation/opentelemetry-instrumentation-asgi/tests/test_asgi_middleware.py#L641

**Comment by samuelcolvin** [comment]
Will do.

**Comment by alexmojaki** [comment]
How about renaming the attribute to `asgi.event.type` or `asgi.message.type`?

**Comment by samuelcolvin** [comment]
Okay, I've fixed tests, but on balance I think I agree with @alexmojaki that we should keep `type` but all it something more descriptive.

> Could you remove the type attribute from the tests? in the test_asgi_middleware.py file
> 
> https://github.com/open-telemetry/opentelemetry-python-contrib/blob/6c13a5eddce4c8446805759bf099a3e79dcd9083/instrumentation/opentelemetry-instrumentation-asgi/tests/test_asgi_middleware.py#L641

No, that's the ASGI `type` in an ASGI scope, which has to be there. 🤦

**Comment by Kludex** [comment]
> How about renaming the attribute to `asgi.event.type` or `asgi.message.type`?

Yeah. I'd call it `asgi.event.type`, but message and event are used as synonymous in the ecosystem.

**Comment by samuelcolvin** [comment]
replaced by #2300.

**Pull request closed without merging**
