### PR TITLE
fix(django): avoid empty span name on empty path

### LINKED ISSUE #1098: [instrumentation-django] - empty span name
**Describe your environment** 
opentelemetry-instrumentation-django==0.30b1
django==4.0.4

**Steps to reproduce**
Having the following URL patterns:
`from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
]`
Please note that the path route has an empty value.

**What is the expected behavior?**
The expected behavior is not having an empty span name for this endpoint.
Also, consider returning http.route  attribute with value '/'

**What is the actual behavior?**
* Got an empty span name
* No http.route attribute returned

### PR DESCRIPTION
**Pull request by muncus**
# Description

when using `path('',...)`, previous code produces spans with an empty
string name. I believe this contradicts the spec, and causes failures in some
exporters (at least the Google Cloud Trace exporter).

This change corrects this fallback behavior and adds a test.
Fixes #1098

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

The included test fails without the corresponding code change.

# Does This PR Require a Core Repo Change?

- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by shalevr** [comment]
> I believe this contradicts the spec

Im not sure about that. Can you link the spec source?

**Comment by muncus** [comment]
> > I believe this contradicts the spec
> 
> Im not sure about that. Can you link the spec source?

The [Span Creation](https://opentelemetry.io/docs/specification/otel/trace/api/#span-creation) section says that Span name is a required parameter. I took this to mean a non-empty name, but that is just my interpretation.

**Comment by muncus** [comment]
Hi folks, this PR has been idle for a week. What is needed to move this forward?

**Review by srikanthccv — APPROVED** [review]

**Review by shalevr — APPROVED** [review]

**Comment by shalevr** [comment]
Could you please fix the tests?

**Comment by muncus** [comment]
Apologies for the delay -- I believe the tests should be fixed now.

Note that i had to re-add a conditional to use the name of the url matcher, because [it was removed](https://github.com/open-telemetry/opentelemetry-python-contrib/commit/743ac64661897087f2dca7f696e481648eb4d0fe#diff-823ff1f241281c88315d2c8eefa856632c936364e0a8e0ad071455598a41a754) in #1759.

**Pull request merged**
