### PR TITLE
Fix elastic-search sanitization for bulk queries

### LINKED ISSUE #1868: Elasticsearch sanitization does not work for bulk queries
**Describe your environment**

Discovered in elasticsearch 5.5.3 and elasticsearch-dsl 5.4.0 and caused by moving to the default sanitization in #1758.

The issue is illustrated here where `body` comes in as a string, not as a dictionary:

image

This is caseud by the bulk flow specifically as the body gets translated to a string here:

image

which looks like this:

image

**Steps to reproduce**

I don't have a super straightforward way to reproduce other than to use the bulk API from elasticsearch.

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**

The below stacktrace:

```
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/someenv/lib/python3.11/site-packages/elasticsearch/helpers/__init__.py", line 95, in _process_bulk_chunk
    resp = client.bulk('\n'.join(bulk_actions) + '\n', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/someenv/lib/python3.11/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/someenv/lib/python3.11/site-packages/elasticsearch/client/__init__.py", line 1173, in bulk
    return self.transport.perform_request('POST', _make_path(index,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/someenv/lib/python3.11/site-packages/opentelemetry/instrumentation/elasticsearch/__init__.py", line 224, in wrapper
    attributes[SpanAttributes.DB_STATEMENT] = sanitize_body(
                                              ^^^^^^^^^^^^^^
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/someenv/lib/python3.11/site-packages/opentelemetry/instrumentation/elasticsearch/utils.py", line 54, in sanitize_body
    flatten_body = _flatten_dict(body)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/someenv/lib/python3.11/site-packages/opentelemetry/instrumentation/elasticsearch/utils.py", line 30, in _flatten_dict
    for k, v in d.items():
                ^^^^^^^
AttributeError: 'str' object has no attribute 'items'

```

**Additional context**

### PR DESCRIPTION
**Pull request by nemoshlag**
# Description

Older elastic search (5.5.3 and below) return 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1868 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] tox -e test-instrumentation-elasticsearch

# Does This PR Require a Core Repo Change?

- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [X] Changelogs have been updated
- [X] Unit tests have been added

### CODE REVIEW

**Review by shalevr — APPROVED** [review]
LGTM

**Comment by shalevr** [comment]
@phillipuniverse Could you please review it?

**Review by phillipuniverse — APPROVED** [review]
This does work, although I’m a bit worried about performance here from deserializing what Elasticsearch already serialized. It might be slightly better to catch the query prior to serialization and sanitize it then. But maybe this is only a problem in ES 5.5?

**Comment by phillipuniverse** [comment]
And overall if someone doesn’t want this behavior they can turn off query sanitzation altogether.

**Comment by shalevr** [comment]
> This does work, although I’m a bit worried about performance here from deserializing what Elasticsearch already serialized. It might be slightly better to catch the query prior to serialization and sanitize it then. But maybe this is only a problem in ES 5.5?

Indeed, it seems to happen only for old versions, According to https://github.com/open-telemetry/opentelemetry-specification/pull/3127 you should always collect db.statement if there is sanitization so you can't just turn off query sanitization.

**Pull request merged**
